/* eslint-disable quotes */
export function getOptions() {
  return [
    {
      code: 'CDR3',
      label: 'CDR3',
      kind: 'C',
      description: 'CDR3 (Complementarity determining region 3). Cys from V region and Phe/Trp from J region included.',
      colorCategory: 'NA',
      equalsTo: '{CDR3Begin:CDR3End}',
    },
    {
      code: 'VDJRegion',
      label: 'VDJ region',
      kind: 'C',
      description: "Full V, D, J assembly without 5'UTR and leader sequence.",
      colorCategory: 'NA',
      equalsTo: '{FR1Begin:FR4End}',
    },
    {
      code: 'CDR1_TO_FR4',
      label: 'CDR1 to FR4',
      kind: 'C',
      description: 'Common reference feature used in alignments for cDNA data obtained using Vmix',
      colorCategory: 'NA',
      equalsTo: '{CDR1Begin:FR4End}',
    },
    {
      code: 'VTranscript',
      label: 'V transcript',
      kind: 'C',
      description: "Common reference feature used in alignments for cDNA data obtained using 5'RACE (that may contain UTRs).",
      colorCategory: 'V',
      equalsTo: '{UTR5Begin:L1End} + {L2Begin:VEnd}',
    },
    {
      code: 'VTranscriptWithP',
      label: 'V transcript with P',
      kind: 'C',
      description:
        "Common reference feature used in alignments for cDNA data obtained using 5'RACE (that may contain UTRs). Contains reference for P region.",
      colorCategory: 'V',
      equalsTo: '{UTR5Begin:L1End} + {L2Begin:VEnd} + {VEnd:VEnd (-20)}',
    },
    {
      code: 'VDJTranscript',
      label: 'VDJ transcript',
      kind: 'C',
      description: "First two exons with 5'UTR of IG/TCR gene.",
      colorCategory: 'V',
      equalsTo: '{UTR5Begin:L1End} + {L2Begin:FR4End}',
    },
    {
      code: 'VTranscriptWithout5UTR',
      label: 'V transcript without 5’UTR',
      kind: 'C',
      description: "Common reference feature used in alignments for mRNA data obtained without 5'RACE.",
      colorCategory: 'V',
      equalsTo: '{L1Begin:L1End} + {L2Begin:VEnd})',
    },
    {
      code: 'VTranscriptWithout5UTRWithP',
      label: 'V transcript without 5’UTR with P',
      kind: 'C',
      description: "Common reference feature used in alignments for mRNA data obtained without 5'RACE. Contains reference for P region.",
      colorCategory: 'V',
      equalsTo: '{L1Begin:L1End} + {L2Begin:VEnd} + {VEnd:VEnd (-20)}',
    },
    {
      code: 'VDJTranscriptWithout5UTR',
      label: 'VDJ transcript without 5’UTR',
      kind: 'C',
      description: 'First two exons of IG/TCR gene.',
      colorCategory: 'V',
      equalsTo: '{L1Begin:L1End} + {L2Begin:FR4End}',
    },
    {
      code: 'VGene',
      label: 'V gene',
      kind: 'C',
      description: 'Common reference feature used in alignments for genomic DNA data.',
      colorCategory: 'V',
      equalsTo: '{UTR5Begin:VEnd}',
    },
    {
      code: 'VGeneWithP',
      label: 'V gene with P',
      kind: 'C',
      description: 'Common reference feature used in alignments for genomic DNA data. Contains reference for P region.',
      colorCategory: 'V',
      equalsTo: '{V5UTRBegin:VEnd}',
    },
    {
      code: 'VRegion',
      label: 'V region',
      kind: 'C',
      description: 'Full V Region; germline',
      colorCategory: 'V',
      equalsTo: '{FR1Begin:VEnd}',
    },
    {
      code: 'VRegionWithP',
      label: 'V region with P',
      kind: 'C',
      description: 'Full V Region with P-segment; to be used as alignment reference',
      colorCategory: 'V',
      equalsTo: '{FR1Begin:VEnd} + {VEnd:VEnd (-20)}',
    },
    {
      code: 'VRegionTrimmed',
      label: 'V region Trimmed',
      kind: 'C',
      description: 'Full V Region in rearranged sequence, e.g. after trimming',
      colorCategory: 'V',
      equalsTo: '{FR1Begin:VEndTrimmed}',
    },
    {
      code: 'V5UTR',
      label: 'V 5’UTR',
      kind: 'C',
      description: "5'UTR in aligned sequence; trimmed",
      colorCategory: 'V',
      equalsTo: '{V5UTRBeginTrimmed:V5UTREnd}',
    },
    {
      code: 'V5UTRGermline',
      label: 'V 5’UTR germline',
      kind: 'P',
      description: "5'UTR; germline",
      colorCategory: 'V',
      equalsTo: '{UTR5Begin:V5UTREnd}',
    },
    {
      code: 'L1',
      label: 'L1',
      kind: 'P',
      description: 'Part of lider sequence in first exon. The same as Exon1.',
      colorCategory: 'V',
      equalsTo: '{L1Begin:L1End}',
    },
    {
      code: 'VLIntronL',
      label: 'V L Intron',
      kind: 'C',
      description: 'L1 + VIntron + L2',
      colorCategory: 'V',
      equalsTo: '{L1Begin:L2End}',
    },
    {
      code: 'Exon1',
      label: 'Exon1',
      kind: 'P',
      description: 'First exon. The same as L1.',
      colorCategory: 'V',
      equalsTo: '{L1Begin:L1End}',
    },
    {
      code: 'L',
      label: 'L',
      kind: 'P',
      description: 'Full leader sequence',
      colorCategory: 'V',
      equalsTo: '{L1Begin:L1End} + {L2Begin:L2End}',
    },
    {
      code: 'VIntron',
      label: 'V intron',
      kind: 'P',
      description: 'Intron in V region.',
      colorCategory: 'V',
      equalsTo: '{VIntronBegin:VIntronEnd}',
    },
    {
      code: 'L2',
      label: 'L2',
      kind: 'P',
      description: 'Part of leader sequence in second exon.',
      colorCategory: 'V',
      equalsTo: '{L2Begin:L2End}',
    },
    {
      code: 'Exon2',
      label: 'Exon2',
      kind: 'C',
      description: 'Full second exon of IG/TCR gene.',
      colorCategory: 'V',
      equalsTo: '{L2Begin:FR4End}',
    },
    {
      code: 'VExon2',
      label: 'V exon2',
      kind: 'C',
      description: 'Second exon of V gene.',
      colorCategory: 'V',
      equalsTo: '{L2Begin:VEnd}',
    },
    {
      code: 'VExon2Trimmed',
      label: 'V exon2 trimmed',
      kind: 'C',
      description: 'Second exon of V gene trimmed. Ends within CDR3 in V (D)J rearrangement.',
      colorCategory: 'V',
      equalsTo: '{L2Begin:VEndTrimmed}',
    },
    {
      code: 'FR1',
      label: 'FR1',
      kind: 'P',
      description: 'Framework 1',
      colorCategory: 'V',
      equalsTo: '{FR1Begin:FR1End}',
    },
    {
      code: 'CDR1',
      label: 'CDR1',
      kind: 'P',
      description: 'CDR1 (Complementarity determining region 1)',
      colorCategory: 'V',
      equalsTo: '{CDR1Begin:CDR1End}',
    },
    {
      code: 'FR2',
      label: 'FR2',
      kind: 'P',
      description: 'Framework 2',
      colorCategory: 'V',
      equalsTo: '{FR2Begin:FR2End}',
    },
    {
      code: 'CDR2',
      label: 'CDR2',
      kind: 'P',
      description: 'CDR2 (Complementarity determining region 2)',
      colorCategory: 'V',
      equalsTo: '{CDR2Begin:CDR2End}',
    },
    {
      code: 'FR3',
      label: 'FR3',
      kind: 'P',
      description: 'Framework 3',
      colorCategory: 'V',
      equalsTo: '{FR3Begin:FR3End}',
    },
    {
      code: 'VCDR3Part',
      label: 'V CDR3 part',
      kind: 'C',
      description: 'Part of V region inside CDR3 (commonly starts from Cys)',
      colorCategory: 'V CDR3',
      equalsTo: '{CDR3Begin:VEndTrimmed}',
    },
    {
      code: 'GermlineVCDR3Part',
      label: 'Germline V CDR3 part',
      kind: 'C',
      description: 'Part of V region inside CDR3 (commonly starts from Cys)',
      colorCategory: 'V CDR3',
      equalsTo: '{CDR3Begin:VEnd}',
    },
    {
      code: 'ShortCDR3',
      label: 'Short CDR3',
      kind: 'C',
      description: 'CDR3 (Complementarity determining region 3). Cys from V region and Phe/Trp from J region excluded.',
      colorCategory: 'NA',
      equalsTo: '{CDR3Begin (3):CDR3End (-3)}',
    },
    {
      code: 'VDJunction',
      label: 'VD junction',
      kind: 'C',
      description: 'N region between V and D genes; not defined for loci without D genes and for V (D)J rearrangement with unidentified D region.',
      colorCategory: 'Junction',
      equalsTo: '{VEndTrimmed:DBeginTrimmed})',
    },
    {
      code: 'VJJunction',
      label: 'VJ junction',
      kind: 'C',
      description: 'Region between V and J regions. For loci without D genes - fully composed from non-template nucleotides. May contain D region.',
      colorCategory: 'Junction',
      equalsTo: '{VEndTrimmed:JBeginTrimmed}',
    },
    {
      code: 'VPSegment',
      label: 'V P-segment',
      kind: 'P',
      description: 'P-segment of V gene',
      colorCategory: 'V',
      equalsTo: '{VEnd:VEndTrimmed}',
    },
    {
      code: 'GermlineVPSegment',
      label: 'Germline V P-segment',
      kind: 'P',
      description: 'P-segment of V gene to be used as alignment reference',
      colorCategory: 'V',
      equalsTo: '{VEnd:VEnd (-20)}',
    },
    {
      code: 'DRegion',
      label: 'D region',
      kind: 'P',
      description: 'Full D Region; germline',
      colorCategory: 'D',
      equalsTo: '{DBegin:DEnd}',
    },
    {
      code: 'DLeftSegment',
      label: 'D left segment',
      kind: 'P',
      description: 'Left P-segment of D gene',
      colorCategory: 'D',
      equalsTo: '{DBeginTrimmed:DBegin}',
    },
    {
      code: 'DCDR3Part',
      label: 'D CDR3 part',
      kind: 'P',
      description: 'Full D Region in rearranged sequence, e.g. after trimming',
      colorCategory: 'D',
      equalsTo: '{DBeginTrimmed:DEndTrimmed}',
    },
    {
      code: 'DJJunction',
      label: 'DJ junction',
      kind: 'P',
      description: 'N region between V and D genes; not defined for loci without D genes and for V (D)J rearrangement with unidentified D region.',
      colorCategory: 'Junction',
      equalsTo: '{DEndTrimmed:JBeginTrimmed}',
    },
    {
      code: 'DRightSegment',
      label: 'D right segment',
      kind: 'P',
      description: 'Right P-segment of D gene',
      colorCategory: 'D',
      equalsTo: '{DEnd:DEndTrimmed}',
    },
    {
      code: 'GermlineDPSegment',
      label: 'Germline D P-segment',
      kind: 'P',
      description: 'P-segment of D gene to be used as alignment reference',
      colorCategory: 'D',
      equalsTo: '{DEnd:DBegin})',
    },
    {
      code: 'DRegionWithP',
      label: 'D region with P',
      kind: 'C',
      description: 'Full D Region with P-segment; to be used as alignment reference',
      colorCategory: 'D',
      equalsTo: '{DEnd:DBegin} + {DBegin:DEnd} + {DEnd:DBegin}',
    },
    {
      code: 'JRegion',
      label: 'J region',
      kind: 'C',
      description: 'Full J Region; germline',
      colorCategory: 'J',
      equalsTo: '{JBegin:FR4End}',
    },
    {
      code: 'GermlineJCDR3Part',
      label: 'Germline J CDR3 part',
      kind: 'C',
      description: 'Part of J region inside CDR3 (commonly ends with Phe/Trp)',
      colorCategory: 'J CDR3',
      equalsTo: '{JBegin:CDR3End}',
    },
    {
      code: 'GermlineJPSegment',
      label: 'Germline J P-segment',
      kind: 'C',
      description: 'P-segment of J gene to be used as alignment reference',
      colorCategory: 'J',
      equalsTo: '{JBegin (20):JBegin}',
    },
    {
      code: 'JRegionWithP',
      label: 'J region with P',
      kind: 'C',
      description: 'Full J Region with P-segment; to be used as alignment reference',
      colorCategory: 'J',
      equalsTo: '{JBegin (20):JBegin} + {JBegin:FR4End}',
    },
    {
      code: 'JPSegment',
      label: 'J P-segment',
      kind: 'C',
      description: 'P-segment of J gene',
      colorCategory: 'J',
      equalsTo: '{JBeginTrimmed:JBegin}',
    },
    {
      code: 'JRegionTrimmed',
      label: 'J region trimmed',
      kind: 'C',
      description: 'Full J Region in rearranged sequence, e.g. after trimming',
      colorCategory: 'J',
      equalsTo: '{JBeginTrimmed:FR4End}',
    },
    {
      code: 'JCDR3Part',
      label: 'J CDR3 part',
      kind: 'C',
      description: 'Part of J region inside CDR3 (commonly ends with Phe/Trp)',
      colorCategory: 'J CDR3',
      equalsTo: '{JBeginTrimmed:CDR3End}',
    },
    {
      code: 'FR4',
      label: 'FR4',
      kind: 'P',
      description: 'Framework 4 (J region after CDR3)',
      colorCategory: 'J',
      equalsTo: '{FR4Begin:FR4End}',
    },
    {
      code: 'CExon1',
      label: 'C exon1',
      kind: 'P',
      description: 'First exon of C Region',
      colorCategory: 'C',
      equalsTo: '{CBegin:CExon1End}',
    },
    {
      code: 'CRegion',
      label: 'C region',
      kind: 'P',
      description: 'Full C region',
      colorCategory: 'C',
      equalsTo: '{CBegin:CEnd}',
    },
  ] as const; //
}
