// DO NOT EDIT. This file was generated by oclif-index utility.

import Cmd0 from './commands/build';
import Cmd1 from './commands/prepare';
import Cmd2 from './commands/upload';

// prettier-ignore
export const COMMANDS = {
  'build': Cmd0,
  'prepare': Cmd1,
  'upload': Cmd2,
};
