packages:
  - lib/util/build-configs
  - lib/util/helpers
  - lib/util/sequences

  - lib/model/common
  - lib/model/middle-layer

  - lib/node/ts-helpers
  - lib/node/ts-helpers-oclif
  - lib/node/ts-helpers-winston
  - lib/node/resolve-helper
  - lib/node/node-streams
  - lib/node/computable
  - lib/node/pl-client
  - lib/node/pl-tree
  - lib/node/pl-drivers
  - lib/node/pl-middle-layer
  - lib/node/pl-local
  - lib/node/pl-config

  - lib/ui/uikit

  - tools/tengo-builder
  - tools/oclif-index
  - tools/block-tools
  - tools/package-builder
  - tools/pl-bootstrap

  - sdk/model
  - sdk/workflow-tengo
  - sdk/test
  - sdk/ui-vue

  # Test blocks

  - etc/block-components/enter-numbers/workflow
  - etc/block-components/enter-numbers/model
  - etc/block-components/enter-numbers/ui
  - etc/blocks/enter-numbers

  - etc/blocks/sum-numbers/workflow
  - etc/blocks/sum-numbers/model
  - etc/blocks/sum-numbers/ui
  - etc/blocks/sum-numbers/block

  - etc/blocks/upload-file/workflow
  - etc/blocks/upload-file/model
  - etc/blocks/upload-file/ui
  - etc/blocks/upload-file/block

  - etc/blocks/download-file/workflow
  - etc/blocks/download-file/model
  - etc/blocks/download-file/ui
  - etc/blocks/download-file/block

  - etc/blocks/read-logs/workflow
  - etc/blocks/read-logs/model
  - etc/blocks/read-logs/ui
  - etc/blocks/read-logs/block

  - etc/block-components/ui-examples/workflow
  - etc/block-components/ui-examples/model
  - etc/block-components/ui-examples/ui
  - etc/blocks/ui-examples

  - etc/blocks/model-test/workflow
  - etc/blocks/model-test/model
  - etc/blocks/model-test/ui
  - etc/blocks/model-test/block

  # Tests

  - tests/workflow-tengo
  - tests/helper
  - tests/block-repo
  - tests/config-local-ml-integration
  - tests/drivers-ml-blocks-integration

  # Etc

  - etc/ui-vue-playground
  - etc/uikit-playground
  - etc/ui-vue-docs

catalog:
  # Build

  'typescript': ~5.5.4
  'tsconfig-paths': ^4.2.0
  'tsup': ~8.3.5
  'vite': ^5.4.11
  'rollup-plugin-node-externals': ^7.1.3
  '@rollup/plugin-node-resolve': ^15.3.0
  'vite-plugin-dts': ^4.3.0
  'tsc-alias': ^1.8.10
  'yarpm': ^1.2.0
  'ts-node': ^10.9.2

  # Build util / linters

  'prettier': ^3.4.1
  '@protobuf-ts/plugin': ^2.9.4

  '@changesets/cli': ^2.27.10

  'eslint': ^8.57.1
  '@eslint/js': ^9.13.0
  'typescript-eslint': ^8.11.0
  '@typescript-eslint/eslint-plugin': ^7.18.0
  'eslint-config-prettier': ^9.1.0
  'eslint-plugin-prettier': '^5.2.1'
  'eslint-plugin-vue': '^9.31.0'

  'oclif': ^4.15.29

  'turbo': ^2.3.3

  '@vitejs/plugin-vue': ^5.2.1

  'svgo': ^3.3.2

  # Net

  'undici': ^6.21.0
  '@grpc/grpc-js': ^1.12.2
  '@protobuf-ts/grpc-transport': ^2.9.4
  '@protobuf-ts/runtime': ^2.9.4
  '@protobuf-ts/runtime-rpc': ^2.9.4
  'https-proxy-agent': ^7.0.5
  '@aws-sdk/client-s3': ^3.701.0
  '@aws-sdk/lib-storage': ^3.701.0
  'cacheable-lookup': ^6.1.0

  # Util & other libs

  'utility-types': ^3.11.0
  'denque': ^2.1.0
  'lru-cache': ^11.0.2
  'canonicalize': ^2.0.0
  'long': ^5.2.3
  'mime-types': ^2.1.35
  'semver': ^7.6.3

  'tar': ^7.4.3
  'tar-fs': ^3.0.6
  'decompress': ^4.2.1
  'readline-sync': ^1.4.10

  'zod': ^3.23.8

  'yaml': ^2.6.1

  '@oclif/core': ^4.0.33

  'winston': ^3.17.0

  '@milaboratories/tengo-tester': ^1.5.0
  '@milaboratories/pframes-node': &pframes-version 2.1.0

  'quickjs-emscripten': ^0.31.0

  # UI

  'vue': ^3.5.13
  '@vueuse/core': ^12.0.0
  'vue-tsc': ^2.1.10
  'sass': ~1.81.0
  'vitepress': '1.5.0'
  'highlight.js': '11.10.0'

  '@ag-grid-community/core': &ag-grid ^32.3.3
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/infinite-row-model': *ag-grid
  '@ag-grid-enterprise/server-side-row-model': *ag-grid
  '@ag-grid-community/styles': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/csv-export': *ag-grid
  '@ag-grid-enterprise/core': *ag-grid
  '@ag-grid-enterprise/rich-select': *ag-grid
  '@ag-grid-enterprise/menu': *ag-grid
  '@ag-grid-enterprise/excel-export': *ag-grid
  '@ag-grid-enterprise/clipboard': *ag-grid
  '@ag-grid-enterprise/range-selection': *ag-grid
  '@ag-grid-community/theming': *ag-grid
  '@ag-grid-enterprise/side-bar': *ag-grid
  '@ag-grid-enterprise/column-tool-panel': *ag-grid

  # SW

  '@milaboratories/software-pframes-conv': *pframes-version
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.6

  # Test

  'jest': ^29.7.0
  '@jest/globals': ^29.7.0
  'ts-jest': ^29.2.5
  'vitest': ^2.1.6
  '@faker-js/faker': ^9.2.0
  'happy-dom': ^15.11.7
  'jsdom': ^25.0.1
  '@vue/test-utils': ^2.4.6
  'resize-observer-polyfill': ^1.5.1

  # Types

  '@types/decompress': ^4.2.7
  '@types/readline-sync': ^1.4.8
  '@types/jest': ^29.5.14
  '@types/http-proxy': ^1.17.15
  '@types/node': ~20.16.15
  '@types/eslint__js': ^8.42.3
  '@types/semver': ^7.5.8
  '@types/mime-types': ^2.1.4
  '@types/tar-fs': ^2.0.4

  # To remove

  'lodash': ^4.17.21
  '@types/lodash': ^4.17.13
