packages:
  - lib/util/build-configs
  - lib/util/helpers
  - lib/util/sequences

  - lib/model/common
  - lib/model/middle-layer

  - lib/node/ts-helpers
  - lib/node/ts-helpers-oclif
  - lib/node/ts-helpers-winston
  - lib/node/resolve-helper
  - lib/node/node-streams
  - lib/node/computable
  - lib/node/pl-client
  - lib/node/pl-tree
  - lib/node/pl-drivers
  - lib/node/pl-middle-layer
  - lib/node/pl-local
  - lib/node/pl-config

  - lib/ui/uikit

  - tools/tengo-builder
  - tools/oclif-index
  - tools/block-tools
  - tools/package-builder
  - tools/pl-bootstrap

  - sdk/model
  - sdk/workflow-tengo
  - sdk/test
  - sdk/ui-vue

  # Test blocks

  - etc/block-components/enter-numbers/workflow
  - etc/block-components/enter-numbers/model
  - etc/block-components/enter-numbers/ui
  - etc/blocks/enter-numbers

  - etc/block-components/ui-examples/workflow
  - etc/block-components/ui-examples/model
  - etc/block-components/ui-examples/ui
  - etc/blocks/ui-examples

  # Tests

  - tests/workflow-tengo
  - tests/helper
  - tests/block-repo
  - tests/config-local-ml-integration

  # Etc

  - etc/ui-vue-playground
  - etc/uikit-playground

catalog:
  # Build

  'typescript': ~5.5.4
  'tsconfig-paths': ^4.2.0
  'tsup': ~8.2.4
  'vite': ^5.4.8
  'rollup-plugin-node-externals': ^7.1.3
  '@rollup/plugin-node-resolve': ^15.3.0
  'vite-plugin-dts': ^4.2.3
  'tsc-alias': ^1.8.10
  'yarpm': ^1.2.0
  'ts-node': ^10.9.2

  # Build util / linters

  'prettier': ^3.3.3
  '@protobuf-ts/plugin': ^2.9.4

  '@changesets/cli': ^2.27.9

  'eslint': ^8.57.1
  '@eslint/js': ^9.11.1
  'typescript-eslint': ^8.8.0
  '@typescript-eslint/eslint-plugin': ^7.18.0
  'eslint-config-prettier': ^9.1.0
  'eslint-plugin-prettier': '^5.2.1'
  'eslint-plugin-vue': '^9.28.0'

  'oclif': ^4.15.5

  'turbo': ^2.1.3

  '@vitejs/plugin-vue': ^5.1.4

  # Net

  'undici': ^6.19.8
  '@grpc/grpc-js': ^1.12.0
  '@protobuf-ts/grpc-transport': ^2.9.4
  '@protobuf-ts/runtime': ^2.9.4
  '@protobuf-ts/runtime-rpc': ^2.9.4
  'https-proxy-agent': ^7.0.5
  '@aws-sdk/client-s3': ^3.666.0
  'cacheable-lookup': ^6.1.0

  # Util & other libs

  'utility-types': ^3.11.0
  'denque': ^2.1.0
  'lru-cache': ^11.0.1
  'canonicalize': ^2.0.0
  'long': ^5.2.3
  'mime-types': ^2.1.35
  'semver': ^7.6.3

  'tar': ^7.4.3
  'tar-fs': ^3.0.6
  'decompress': ^4.2.1
  'readline-sync': ^1.4.10

  'zod': ^3.23.8

  'yaml': ^2.5.1

  '@oclif/core': ^4.0.27

  'winston': ^3.14.2

  '@milaboratories/tengo-tester': ^1.4.4
  '@milaboratories/pframes-node': &pframes-version ^1.5.10

  'quickjs-emscripten': ^0.31.0

  # UI

  'vue': ^3.5.11
  '@vueuse/core': ^11.1.0
  'vue-tsc': ^2.1.6
  'sass': ~1.77.8

  '@ag-grid-community/client-side-row-model': ^32.2.2
  '@ag-grid-community/core': ^32.2.2
  '@ag-grid-community/infinite-row-model': ^32.2.2
  '@ag-grid-community/styles': ^32.2.2
  '@ag-grid-community/vue3': ^32.2.2
  '@ag-grid-enterprise/core': ^32.2.2
  '@ag-grid-enterprise/clipboard': ^32.2.2
  '@ag-grid-enterprise/range-selection': ^32.2.2

  # SW

  '@milaboratories/software-pframes-conv': *pframes-version
  '@milaboratories/software-small-binaries': ^1.10.4

  # Test

  'jest': ^29.7.0
  '@jest/globals': ^29.7.0
  'ts-jest': ^29.2.5
  'vitest': ^2.1.2
  '@faker-js/faker': ^8.4.1
  'happy-dom': ^14.12.3
  'jsdom': ^24.1.3
  '@vue/test-utils': ^2.4.6
  'resize-observer-polyfill': ^1.5.1

  # Types

  '@types/decompress': ^4.2.7
  '@types/readline-sync': ^1.4.8
  '@types/jest': ^29.5.13
  '@types/http-proxy': ^1.17.15
  '@types/node': ~20.16.10
  '@types/eslint__js': ^8.42.3
  '@types/semver': ^7.5.8
  '@types/mime-types': ^2.1.4
  '@types/tar-fs': ^2.0.4

  # To remove

  'lodash': ^4.17.21
  '@types/lodash': ^4.17.10
