packages:
  - lib/util/build-configs
  - lib/util/helpers
  - lib/util/sequences

  - lib/other/aioli-main

  - lib/model/common
  - lib/model/middle-layer
  - lib/model/backend

  - lib/node/ts-helpers
  - lib/node/ts-helpers-oclif
  - lib/node/ts-helpers-winston
  - lib/node/pl-http
  - lib/node/pl-errors
  - lib/model/pl-error-like

  - lib/node/resolve-helper
  - lib/node/node-streams
  - lib/node/computable
  - lib/node/pl-client
  - lib/node/pl-tree
  - lib/node/pl-drivers
  - lib/node/pl-middle-layer
  - lib/node/pl-deployments
  - lib/node/pl-config

  - lib/ui/uikit

  - tools/tengo-builder
  - tools/oclif-index
  - tools/block-tools
  - tools/package-builder
  - tools/r-builder
  - tools/pl-bootstrap
  - tools/eslint-config

  - sdk/model
  - sdk/workflow-tengo
  - sdk/test
  - sdk/ui-vue
  - sdk/eslint-config

  # Test blocks

  - etc/blocks/enter-numbers/workflow
  - etc/blocks/enter-numbers/model
  - etc/blocks/enter-numbers/ui
  - etc/blocks/enter-numbers/block

  - etc/blocks/sum-numbers/workflow
  - etc/blocks/sum-numbers/model
  - etc/blocks/sum-numbers/ui
  - etc/blocks/sum-numbers/block

  - etc/blocks/upload-file/workflow
  - etc/blocks/upload-file/model
  - etc/blocks/upload-file/ui
  - etc/blocks/upload-file/block

  - etc/blocks/blob-url-custom-protocol/workflow
  - etc/blocks/blob-url-custom-protocol/model
  - etc/blocks/blob-url-custom-protocol/ui
  - etc/blocks/blob-url-custom-protocol/block

  - etc/blocks/monetization-test/workflow
  - etc/blocks/monetization-test/model
  - etc/blocks/monetization-test/ui
  - etc/blocks/monetization-test/block

  - etc/blocks/download-file/workflow
  - etc/blocks/download-file/model
  - etc/blocks/download-file/ui
  - etc/blocks/download-file/block

  - etc/blocks/read-logs/workflow
  - etc/blocks/read-logs/model
  - etc/blocks/read-logs/ui
  - etc/blocks/read-logs/block

  - etc/blocks/ui-examples/workflow
  - etc/blocks/ui-examples/model
  - etc/blocks/ui-examples/ui
  - etc/blocks/ui-examples/block

  - etc/blocks/model-test/workflow
  - etc/blocks/model-test/model
  - etc/blocks/model-test/ui
  - etc/blocks/model-test/block

  - etc/blocks/pool-explorer/workflow
  - etc/blocks/pool-explorer/model
  - etc/blocks/pool-explorer/ui
  - etc/blocks/pool-explorer/block

  # Tests

  - tests/workflow-tengo
  - tests/helper
  - tests/block-repo
  - tests/config-local-ml-integration
  - tests/drivers-ml-blocks-integration

  - tests/package-builder/10.asset
  - tests/package-builder/20.runenv
  - tests/package-builder/30.software-pkg
  - tests/package-builder/90.catalogue

  # Etc

  - etc/ui-vue-playground
  - etc/uikit-playground
  - etc/ui-vue-docs

catalog:
  # Build
  'typescript': ~5.5.4
  'tsconfig-paths': ^4.2.0
  'tsup': ~8.3.5
  # 'vite': ^6.0.3
  'vite': ^5.4.11
  'rollup-plugin-node-externals': ^7.1.3
  '@rollup/plugin-node-resolve': ^16.0.1
  'rollup-plugin-sourcemaps2': ^0.5.0
  'vite-plugin-dts': ^4.5.3
  'tsc-alias': ^1.8.11
  'yarpm': ^1.2.0
  'ts-node': ^10.9.2

  # Build util / linters

  'prettier': ^3.4.1
  '@protobuf-ts/plugin': &protobuf-ts 2.9.6

  '@changesets/cli': ^2.29.2

  'eslint': ^9.25.1
  '@eslint/js': ^9.16.0
  'typescript-eslint': ^8.17.0
  'eslint-config-prettier': ^9.1.0
  'eslint-plugin-prettier': '^5.1.3'
  'eslint-plugin-vue': '^9.26.0'
  '@stylistic/eslint-plugin': ^2.11.0
  'eslint-plugin-import': ^2.31.0
  'eslint-plugin-n': ^17.12.0
  'globals': ^15.13.0

  'oclif': ^4.16.2

  'turbo': ^2.5.2

  '@vitejs/plugin-vue': ^5.2.3

  'svgo': ^3.3.2

  'rimraf': ^6.0.1

  # Net

  'undici': ~7.5.0
  '@grpc/grpc-js': ~1.13.1
  '@protobuf-ts/grpc-transport': *protobuf-ts
  '@protobuf-ts/runtime': *protobuf-ts
  '@protobuf-ts/runtime-rpc': *protobuf-ts
  'https-proxy-agent': ^7.0.6
  '@aws-sdk/client-s3': &aws-sdk-version 3.775.0
  '@aws-sdk/lib-storage': *aws-sdk-version

  # Util & other libs

  'testcontainers': ^10.18.0
  'utility-types': ^3.11.0
  'denque': ^2.1.0
  'lru-cache': ^11.1.0
  'canonicalize': ~2.1.0
  'long': ^5.3.1
  'mime-types': ^2.1.35
  'semver': ^7.6.3

  'upath': ^2.0.1
  'tar': ^7.4.3
  'tar-fs': ^3.0.8
  'decompress': ^4.2.1
  'readline-sync': ^1.4.10
  'ssh2': ^1.16.0
  'json-stringify-safe': ^5.0.1

  'fs-extra': '^11.2.0'

  # dont upgrade, ask @dbolotin first
  'zod': ~3.23.8

  'yaml': ^2.7.0

  '@oclif/core': ^4.0.37

  'winston': ^3.17.0

  '@milaboratories/tengo-tester': ^1.6.1
  '@milaboratories/pframes-rs-node': &pframes-rs-version 1.0.39

  'remeda': ^2.21.2

  'quickjs-emscripten': 0.31.0

  # UI

  'vue': ^3.5.13
  # TODO upgrade (see https://github.com/vueuse/vueuse/pull/4543)
  # '@vueuse/core': ^12.8.2
  '@vueuse/core': ~12.4.0
  'vue-tsc': ^2.1.10
  'sass': ~1.83.4
  'vitepress': '1.5.0'
  'highlight.js': '11.10.0'
  'd3': '^7.9.0'
  '@types/d3': '^7.4.3'
  'd3-format': ^3.1.0
  '@types/d3-format': ^3.0.4

  'ag-grid-enterprise': &ag-grid ^33.0.4
  'ag-grid-vue3': *ag-grid

  '@milaboratories/miplots4': ^1.0.98

  'monaco-editor': ^0.52.2

  # SW

  '@milaboratories/software-pframes-conv': &pframes-version 2.2.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.21
  '@platforma-open/milaboratories.software-ptabler': 1.6.0
  '@biowasm/aioli': ~3.2.1

  # Test

  'jest': ^29.7.0
  '@jest/globals': ^29.7.0
  'ts-jest': ^29.2.6
  'vitest': ^2.1.9
  '@vitest/coverage-v8': ^2.1.9
  '@faker-js/faker': ^9.2.0
  'happy-dom': ^15.11.7
  'jsdom': ^25.0.1
  '@vue/test-utils': ^2.4.6
  'resize-observer-polyfill': ^1.5.1

  # Types

  '@types/json-stringify-safe': ^5.0.3
  '@types/decompress': ^4.2.7
  '@types/readline-sync': ^1.4.8
  '@types/jest': ^29.5.14
  '@types/http-proxy': ^1.17.16
  '@types/node': ~20.16.15
  '@types/eslint__js': ^8.42.3
  '@types/semver': ^7.5.8
  '@types/mime-types': ^2.1.4
  '@types/tar-fs': ^2.0.4
  '@types/ssh2': ^1.15.1

  # To remove

  'lodash': ^4.17.15
  '@types/lodash': ^4.17.16
