// Guard against releasing software that cannot run where we deploy it.
//
// Nothing else requires a docker variant: an image is autogenerated only for
// `python` and `conda` artifacts (`artifacts.dockerAutogenTypes`), so a `java`,
// `R` or plain `binary` entrypoint without an explicit `docker:` block writes a
// descriptor carrying `binary` and nothing else. Every Platforma installation
// is kubernetes-based, and the k8s runner has no binary fallback — it fails the
// command with a bare "docker image is not specified". CI stays green, the
// defect surfaces the first time a user runs the block (MILAB-6872).
//
// So: in CI, describing a software entrypoint that produces no image is an
// error, unless the package declares itself binary-only with
// `"block-software": { "requireDocker": false }`.
//
// The check reads the package's declaration, not what this particular run
// built: `--variant binary` and other partial builds are legitimate, a
// misdeclared entrypoint is not.

import * as docker from "./docker";
import * as envs from "./envs";
import type * as entrypoint from "./schemas/entrypoints";
import * as util from "./util";

export type DockerCoverage = {
  /** Names of software entrypoints that produce no docker image. */
  softwareWithoutDocker: string[];
  /** Package opted out with `"block-software": { "requireDocker": false }`. */
  requirementWaived: boolean;
};

/**
 * The software entrypoints among `entrypoints` that yield no docker image.
 *
 * `entrypoints` is expected in the shape `PackageInfo.entrypoints` produces:
 * one entry per declared entrypoint plus a virtual `<name>:docker` companion
 * for every entrypoint that has an image, explicit or autogenerated. So a
 * missing companion is the whole signal.
 *
 * Run environments and assets are not software and never carry an image of
 * their own (a python image bakes its environment in), so they are skipped —
 * as are docker-only entrypoints, which have no plain entry to pair with.
 */
export function softwareEntrypointsWithoutDocker(
  entrypoints: Map<string, entrypoint.Entrypoint>,
): string[] {
  const uncovered: string[] = [];

  for (const [name, ep] of entrypoints.entries()) {
    if (docker.isVirtualDockerEntrypointName(name)) continue;
    if (ep.type !== "software") continue;
    if (entrypoints.has(docker.entrypointName(name))) continue;

    uncovered.push(name);
  }

  return uncovered;
}

/** Throws when CI is about to describe software that no k8s install can run. */
export function assertDockerCoverage(coverage: DockerCoverage): void {
  if (!envs.isCI()) return;
  if (coverage.requirementWaived) return;
  if (coverage.softwareWithoutDocker.length === 0) return;

  const list = coverage.softwareWithoutDocker.map((name) => `    - ${name}`).join("\n");

  throw util.CLIError(
    `These software entrypoints produce no docker image, so no kubernetes installation ` +
      `can run them:\n${list}\n` +
      `  An image is autogenerated only for 'python' and 'conda' artifacts. Give each ` +
      `entrypoint above an explicit 'docker' block next to its 'binary' one.\n` +
      `  If this package really is meant to be binary-only, declare that with ` +
      `"block-software": { "requireDocker": false }.`,
  );
}
