// DO NOT EDIT. This file was generated by oclif-index utility.

import Cmd0 from './build-meta';
import Cmd1 from './build-model';
import Cmd3 from './list-overview-snapshots';
import Cmd4 from './mark-stable';
import Cmd5 from './pack';
import Cmd6 from './publish';
import Cmd7 from './refresh-registry';
import Cmd8 from './restore-overview-from-snapshot';
import Cmd9 from './upload-package-v1';

// prettier-ignore
export const COMMANDS = {
  'build-meta': Cmd0,
  'build-model': Cmd1,
  'list-overview-snapshots': Cmd3,
  'mark-stable': Cmd4,
  'pack': Cmd5,
  'publish': Cmd6,
  'refresh-registry': Cmd7,
  'restore-overview-from-snapshot': Cmd8,
  'upload-package-v1': Cmd9,
};
