// DO NOT EDIT. This file was generated by oclif-index utility.

import Cmd0 from "./build-meta";
import Cmd1 from "./build-model";
import Cmd3 from "./list-overview-snapshots";
import Cmd4 from "./mark-stable";
import Cmd5 from "./pack";
import Cmd6 from "./publish";
import Cmd7 from "./refresh-registry";
import Cmd8 from "./restore-overview-from-snapshot";
import Cmd9 from "./update-deps";
import Cmd10 from "./upload-package-v1";
import Cmd11 from "./structure/check";
import Cmd12 from "./structure/init";
import Cmd13 from "./structure/refresh";

export const COMMANDS = {
  "build-meta": Cmd0,
  "build-model": Cmd1,
  "list-overview-snapshots": Cmd3,
  "mark-stable": Cmd4,
  pack: Cmd5,
  publish: Cmd6,
  "refresh-registry": Cmd7,
  "restore-overview-from-snapshot": Cmd8,
  "update-deps": Cmd9,
  "upload-package-v1": Cmd10,
  "structure:check": Cmd11,
  "structure:init": Cmd12,
  "structure:refresh": Cmd13,
};
