import * as v from "valibot";
import type { InferSnapshot } from "@milaboratories/pl-tree";
import { rsSchema } from "@milaboratories/pl-tree";
import { RangeBytes } from "@milaboratories/pl-model-common";

//
// download
//
/** ResourceSnapshot that can be passed to OnDemandBlob */
export const OnDemandBlobResourceSnapshot = rsSchema({
  kv: {
    "ctl/file/blobInfo": v.object({
      sizeBytes: v.pipe(v.unknown(), v.transform(Number), v.number()),
    }),
  },
});

export type OnDemandBlobResourceSnapshot = InferSnapshot<typeof OnDemandBlobResourceSnapshot>;

export function getSize(bs: OnDemandBlobResourceSnapshot, range?: RangeBytes): number {
  const size = bs.kv["ctl/file/blobInfo"].sizeBytes;
  if (range) {
    const newSize = range.to - range.from;
    if (newSize > size) {
      throw new Error(
        `getSize: range (${JSON.stringify(range)}, newSize: ${newSize}) is greater than size (${size})`,
      );
    }

    return newSize;
  }

  return size;
}

//
// upload
//

export const ImportFileHandleUploadData = v.object({
  /** Local file path, to take data for upload */
  localPath: v.string(),
  /** Path signature, to check this data was generated by us */
  pathSignature: v.string(),
  /** File size in bytes */
  sizeBytes: v.string(),
  /** Modification time unix timestamp in seconds */
  modificationTime: v.string(),
});
export type ImportFileHandleUploadData = v.InferOutput<typeof ImportFileHandleUploadData>;

export const ImportFileHandleIndexData = v.object({
  /** Pl storage id */
  storageId: v.string(),
  /** Path inside storage */
  path: v.string(),
  /**
   * Federative identity envelope from LsAPI.List.Response.ListItem.additional_info.
   * Absent for non-federative storages (backwards compatible: old handles parse unchanged).
   */
  additionalInfo: v.optional(v.record(v.string(), v.string())),
});
export type ImportFileHandleIndexData = v.InferOutput<typeof ImportFileHandleIndexData>;

export const ImportFileHandleData = v.union([
  ImportFileHandleUploadData,
  ImportFileHandleIndexData,
]);
export type ImportFileHandleData = v.InferOutput<typeof ImportFileHandleData>;

/** Options from BlobUpload resource that have to be passed to getProgress. */

/** ResourceSnapshot that can be passed to GetProgressID */
export const UploadResourceSnapshot = rsSchema({
  data: ImportFileHandleUploadData,
  fields: {
    blob: false,
  },
});

export const IndexResourceSnapshot = rsSchema({
  fields: {
    incarnation: false,
  },
});

export type UploadResourceSnapshot = InferSnapshot<typeof UploadResourceSnapshot>;
export type IndexResourceSnapshot = InferSnapshot<typeof IndexResourceSnapshot>;

export type ImportResourceSnapshot = UploadResourceSnapshot | IndexResourceSnapshot;

//
// ls
//

/** Defines which storages from pl are available via local paths */
export type LocalStorageProjection = {
  /** Pl storage id */
  readonly storageId: string;

  /**
   * Local path, the storage is mounted at.
   *
   * Empty string means that this storage accepts absolute paths, and operates inside the same OS.
   * This matches the behaviour how pl interprets FS storage config.
   * */
  readonly localPath: string;
};

/** Allows to add parts of local FS as virtual storages, presenting homogeneous API to UI */
export type VirtualLocalStorageSpec = {
  /** Stable machine identifier, must not intersect with other storage ids */
  readonly id: string;
  /** Human-readable display name */
  readonly name: string;

  /** Local path to "chroot" the API in */
  readonly root: string;

  /** Used as hint to UI controls to, set as initial path during browsing */
  readonly initialPath: string;
};
