/** Well-known resource type names used across the platform. */
export const ResourceTypeName = {
  StreamManager: "StreamManager",
  StdMap: "StdMap",
  StdMapSlash: "std/map",
  EphStdMap: "EphStdMap",
  PFrame: "PFrame",
  ParquetChunk: "ParquetChunk",
  BContext: "BContext",
  BlockPackCustom: "BlockPackCustom",
  BinaryMap: "BinaryMap",
  BinaryValue: "BinaryValue",
  BlobMap: "BlobMap",
  BResolveSingle: "BResolveSingle",
  BResolveSingleNoResult: "BResolveSingleNoResult",
  BQueryResult: "BQueryResult",
  TengoTemplate: "TengoTemplate",
  TengoLib: "TengoLib",
  SoftwareInfo: "SoftwareInfo",
  Dummy: "Dummy",
  JsonResourceError: "json/resourceError",
  JsonObject: "json/object",
  JsonGzObject: "json-gz/object",
  JsonString: "json/string",
  JsonArray: "json/array",
  JsonNumber: "json/number",
  BContextEnd: "BContextEnd",
  FrontendFromUrl: "Frontend/FromUrl",
  FrontendFromFolder: "Frontend/FromFolder",
  BObjectSpec: "BObjectSpec",
  Blob: "Blob",
  Null: "Null",
  Binary: "binary",
  LSProvider: "LSProvider",
  UserProject: "UserProject",
  Projects: "Projects",
  ClientRoot: "ClientRoot",
} as const;

/** Resource type name prefix constants. */
export const ResourceTypePrefix = {
  Blob: "Blob/",
  BlobUpload: "BlobUpload/",
  BlobIndex: "BlobIndex/",
  PColumnData: "PColumnData/",
  StreamWorkdir: "StreamWorkdir/",
} as const;
