import * as v from "valibot";
import * as defaults from "../../defaults";
import * as util from "../util";

// All known artifact types
export const artifactTypes = [
  "asset",
  "environment",
  "binary",
  "java",
  "python",
  "R",
  "docker",
  "conda",
] as const;
export type artifactType = (typeof artifactTypes)[number];

// TODO: change these to type definitions, not arrays. This will simplify type narrowing logic throughout the code.
export const archiveArtifactTypes: artifactType[] = [
  "asset",
  "environment",
  "binary",
  "java",
  "python",
  "R",
  "conda",
] as const;
export const crossplatformTypes: artifactType[] = ["asset", "java", "python", "R"] as const;
export const dockerAutogenTypes: artifactType[] = ["python", "conda"] as const;
export const dockerArchitectures: util.ArchType[] = ["x64"] as const;

export function isBuildable(aType: artifactType): boolean {
  // All known artifact types are buildable. No exceptions so far.
  return artifactTypes.includes(aType);
}

export function isCrossPlatform(aType: artifactType): boolean {
  return crossplatformTypes.includes(aType);
}

export const runEnvironmentTypes = ["java", "python", "R"] as const;
export type runEnvironmentType = (typeof runEnvironmentTypes)[number];

export const pythonToolsets = ["pip"] as const;
export type pythonToolsetName = (typeof pythonToolsets)[number];

export const registrySchema = v.strictObject({
  name: v.string(),
  downloadURL: v.optional(v.string()),
  storageURL: v.optional(v.string()),
});
export type registry = v.InferOutput<typeof registrySchema>;

export const registryOrRef = v.union([v.string(), registrySchema]);

// common fields for all buildable artifacts
// TODO: create new type for binary packages
const archiveRulesSchema = v.object({
  registry: v.optional(registryOrRef, {
    name: defaults.BIN_REGISTRY_NAME,
    downloadURL: defaults.BIN_REGISTRY_DOWNLOAD_URL,
  }),

  name: v.optional(v.string()),
  version: v.optional(v.string()),

  root: v.string("package archive content directory is required"),
  roots: v.pipe(
    v.record(
      v.picklist(util.AllPlatforms),
      v.pipe(v.string("path to package archive content directory cannot be empty"), v.minLength(1)),
      "list of supported platforms is required: { <platform>: <dir> }\n" +
        "supported platforms:\n  " +
        util.AllPlatforms.join("\n  "),
    ),
    v.check(
      (val) => Object.keys(val).length > 0,
      "specify at least one platform supported by this software in format: { <platform>: <dir> }\n" +
        "supported platforms:\n  " +
        util.AllPlatforms.join("\n  "),
    ),
    v.description(
      "please, provide settings only for supported platforms: " + util.AllPlatforms.join(", "),
    ),
  ),
});
export type archiveRules = v.InferOutput<typeof archiveRulesSchema>;

const dockerRulesSchema = v.object({
  ["docker-registry"]: v.optional(
    v.pipe(
      v.string(
        "python software is also automatically shipped as docker image. Docker registry cannot be empty",
      ),
      v.minLength(1),
      v.description("registry to use for pushing autogenerated docker image"),
    ),
    defaults.DOCKER_REGISTRY,
  ),

  pkg: v.optional(
    v.pipe(
      v.string(),
      v.description(
        '{pkg} placeholder value to be used in "cmd" and arguments (for docker autogeneration)',
      ),
    ),
    defaults.DOCKER_PLACEHOLDER_PKG,
  ),
});

export const artifactIDSchema = v.pipe(
  v.string(),
  v.regex(
    /:/,
    "tengo artifact ID must have <npmPackage>:<artifactName> format, e.g @milaboratory/runenv-java-corretto:21.2.0.4.1",
  ),
  v.description("ID of tengo build artifact"),
);

export type artifactIDString = v.InferOutput<typeof artifactIDSchema>;

export const assetSchema = v.strictObject({
  ...v.omit(archiveRulesSchema, ["roots"]).entries,
  type: v.literal("asset"),
});
export type assetType = v.InferOutput<typeof assetSchema>;

export const environmentSchema = v.object({
  ...v.omit(archiveRulesSchema, ["root"]).entries,
  type: v.literal("environment"),

  runtime: v.pipe(
    v.picklist(runEnvironmentTypes),
    v.description("type of runtime this run environment provides: 'java', 'python' and so on"),
  ),

  ["r-version"]: v.optional(v.string()),
  ["python-version"]: v.optional(v.string()),
  ["java-version"]: v.optional(v.string()),

  envVars: v.optional(
    v.array(
      v.pipe(
        v.string(),
        v.regex(
          /=/,
          "environment variable should be specified in format: <var-name>=<var-value>, i.e.: MY_ENV=value",
        ),
      ),
    ),
  ),

  binDir: v.pipe(
    v.string(),
    v.description(
      "path to 'bin' directory to be added to PATH when software uses this run environment",
    ),
  ),
});

export type environmentType = v.InferOutput<typeof environmentSchema>;

export const binarySchema = v.object({
  ...v.omit(archiveRulesSchema, ["root"]).entries,
  type: v.literal("binary"),
});
export type binaryType = v.InferOutput<typeof binarySchema>;

export const javaSchema = v.object({
  ...v.omit(archiveRulesSchema, ["roots"]).entries,
  type: v.literal("java"),
  environment: artifactIDSchema,
});
export type javaType = v.InferOutput<typeof javaSchema>;

const pipToolsetSchema = v.strictObject({
  toolset: v.literal("pip"),
  requirements: v.pipe(v.string(), v.description("path to requrements.txt inside package archive")),
});

export const pythonToolsetSchema = v.variant("toolset", [pipToolsetSchema]);

export const pythonSchema = v.object({
  ...v.omit(archiveRulesSchema, ["roots"]).entries,
  ...dockerRulesSchema.entries,

  type: v.literal("python"),

  environment: artifactIDSchema,
  dependencies: v.optional(pythonToolsetSchema),
});
export type pythonType = v.InferOutput<typeof pythonSchema>;

export const rSchema = v.object({
  ...v.omit(archiveRulesSchema, ["roots"]).entries,
  type: v.literal("R"),
  environment: artifactIDSchema,
});
export type rType = v.InferOutput<typeof rSchema>;

export const condaSchema = v.object({
  ...v.omit(archiveRulesSchema, ["root"]).entries,
  ...dockerRulesSchema.entries,

  type: v.literal("conda"),

  ["micromamba-version"]: v.optional(
    v.pipe(
      v.string(),
      v.description("version of micromamba to be used to operate with conda environments"),
    ),
    defaults.CONDA_MICROMAMBA_VERSION,
  ),
  ["conda-root-dir"]: v.optional(
    v.pipe(v.string(), v.description("root directory of conda environment inside package root")),
    defaults.CONDA_DATA_LOCATION,
  ),

  spec: v.optional(
    v.pipe(
      v.string(),
      v.description(`path to conda environment yaml specification relative to package.json`),
    ),
    defaults.CONDA_SOURCE_ENV_SPEC_FILE,
  ),
});
export type condaType = v.InferOutput<typeof condaSchema>;

export const dockerSchema = v.object({
  type: v.literal("docker"),

  registry: v.optional(
    v.pipe(v.string(), v.description("registry+repository URL to use for pulling this image")),
    defaults.DOCKER_REGISTRY,
  ),

  // build from custom Dockerfile
  context: v.pipe(
    v.string(),
    v.check(
      (val) => val !== "./" && val !== ".",
      'Context cannot be "./" or "." - use absolute path or relative path without "./" prefix',
    ),
    v.description(
      'relative path to context directory from folder where command is executed or absolute path to context folder (cannot be "./" or ".")',
    ),
  ),

  dockerfile: v.optional(
    v.pipe(
      v.string(),
      v.description(
        "relative path to 'Dockerfile' file from folder where command is executed or absolute path to the file",
      ),
    ),
    defaults.DOCKER_DOCKERFILE,
  ),

  pkg: v.optional(
    v.pipe(v.string(), v.description('{pkg} placeholder value to be used in "cmd" and arguments')),
    defaults.DOCKER_PLACEHOLDER_PKG,
  ),

  // import existing image
  // entrypoint: v.optional(
  //   v.pipe(
  //     v.array(v.string()),
  //     v.description('replace image\'s ENTRYPOINT with this value when running container'),
  //   ),
  // ),
});
export type dockerType = v.InferOutput<typeof dockerSchema>;

export const anyArtifactSchema = v.variant("type", [
  assetSchema,
  environmentSchema,
  binarySchema,
  javaSchema,
  pythonSchema,
  rSchema,
  condaSchema,
  dockerSchema,
]);

export type anyArtifactType = v.InferOutput<typeof anyArtifactSchema>;

export const artifactIndexSchema = v.record(v.string(), anyArtifactSchema);
export type artifactIndexType = v.InferOutput<typeof artifactIndexSchema>;

export type withType<Typ, Orig> = Orig & { type: Typ };
export type withId<T> = T & { id: string };
