// @generated by protobuf-ts 2.9.6 with parameter client_generic,optimize_speed,generate_dependencies,force_server_none
// @generated from protobuf file "github.com/milaboratory/pl/plapi/plapiproto/import.proto" (package "MiLaboratories.PL._Stub", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Struct } from "../../../../../google/protobuf/struct";
import { ListValue } from "../../../../../google/protobuf/struct";
import { Value } from "../../../../../google/protobuf/struct";
import { Timestamp } from "../../../../../google/protobuf/timestamp";
import { Duration } from "../../../../../google/protobuf/duration";
import { DoubleValue } from "../../../../../google/protobuf/wrappers";
import { FloatValue } from "../../../../../google/protobuf/wrappers";
import { UInt64Value } from "../../../../../google/protobuf/wrappers";
import { Int64Value } from "../../../../../google/protobuf/wrappers";
import { UInt32Value } from "../../../../../google/protobuf/wrappers";
import { Int32Value } from "../../../../../google/protobuf/wrappers";
import { StringValue } from "../../../../../google/protobuf/wrappers";
import { BoolValue } from "../../../../../google/protobuf/wrappers";
import { BytesValue } from "../../../../../google/protobuf/wrappers";
import { Any } from "../../../../../google/protobuf/any";
import { Empty } from "../../../../../google/protobuf/empty";
/**
 * Makes protobuf to forcefully compile all well-known types into code (for TS)
 * or just add dependencies on them (for go)
 *
 * @generated from protobuf message MiLaboratories.PL._Stub._ImportWellKnown
 */
export interface _ImportWellKnown {
    /**
     * @generated from protobuf field: google.protobuf.Empty empty = 1;
     */
    empty?: Empty;
    /**
     * @generated from protobuf field: google.protobuf.Any any = 2;
     */
    any?: Any;
    /**
     * @generated from protobuf field: google.protobuf.BytesValue bytes = 3;
     */
    bytes?: BytesValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue bool = 4;
     */
    bool?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue string = 5;
     */
    string?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int32Value int32 = 6;
     */
    int32?: Int32Value;
    /**
     * @generated from protobuf field: google.protobuf.UInt32Value uint32 = 7;
     */
    uint32?: UInt32Value;
    /**
     * @generated from protobuf field: google.protobuf.Int64Value int64 = 8;
     */
    int64?: Int64Value;
    /**
     * @generated from protobuf field: google.protobuf.UInt64Value uint64 = 9;
     */
    uint64?: UInt64Value;
    /**
     * @generated from protobuf field: google.protobuf.FloatValue float = 10;
     */
    float?: FloatValue;
    /**
     * @generated from protobuf field: google.protobuf.DoubleValue double = 11;
     */
    double?: DoubleValue;
    /**
     * @generated from protobuf field: google.protobuf.Duration duration = 12;
     */
    duration?: Duration;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp timestamp = 13;
     */
    timestamp?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Value value = 14;
     */
    value?: Value;
    /**
     * @generated from protobuf field: google.protobuf.ListValue list = 15;
     */
    list?: ListValue;
    /**
     * @generated from protobuf field: google.protobuf.Struct struct = 16;
     */
    struct?: Struct;
}
// @generated message type with reflection information, may provide speed optimized methods
class _ImportWellKnown$Type extends MessageType<_ImportWellKnown> {
    constructor() {
        super("MiLaboratories.PL._Stub._ImportWellKnown", [
            { no: 1, name: "empty", kind: "message", T: () => Empty },
            { no: 2, name: "any", kind: "message", T: () => Any },
            { no: 3, name: "bytes", kind: "message", T: () => BytesValue },
            { no: 4, name: "bool", kind: "message", T: () => BoolValue },
            { no: 5, name: "string", kind: "message", T: () => StringValue },
            { no: 6, name: "int32", kind: "message", T: () => Int32Value },
            { no: 7, name: "uint32", kind: "message", T: () => UInt32Value },
            { no: 8, name: "int64", kind: "message", T: () => Int64Value },
            { no: 9, name: "uint64", kind: "message", T: () => UInt64Value },
            { no: 10, name: "float", kind: "message", T: () => FloatValue },
            { no: 11, name: "double", kind: "message", T: () => DoubleValue },
            { no: 12, name: "duration", kind: "message", T: () => Duration },
            { no: 13, name: "timestamp", kind: "message", T: () => Timestamp },
            { no: 14, name: "value", kind: "message", T: () => Value },
            { no: 15, name: "list", kind: "message", T: () => ListValue },
            { no: 16, name: "struct", kind: "message", T: () => Struct }
        ]);
    }
    create(value?: PartialMessage<_ImportWellKnown>): _ImportWellKnown {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<_ImportWellKnown>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: _ImportWellKnown): _ImportWellKnown {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Empty empty */ 1:
                    message.empty = Empty.internalBinaryRead(reader, reader.uint32(), options, message.empty);
                    break;
                case /* google.protobuf.Any any */ 2:
                    message.any = Any.internalBinaryRead(reader, reader.uint32(), options, message.any);
                    break;
                case /* google.protobuf.BytesValue bytes */ 3:
                    message.bytes = BytesValue.internalBinaryRead(reader, reader.uint32(), options, message.bytes);
                    break;
                case /* google.protobuf.BoolValue bool */ 4:
                    message.bool = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.bool);
                    break;
                case /* google.protobuf.StringValue string */ 5:
                    message.string = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.string);
                    break;
                case /* google.protobuf.Int32Value int32 */ 6:
                    message.int32 = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.int32);
                    break;
                case /* google.protobuf.UInt32Value uint32 */ 7:
                    message.uint32 = UInt32Value.internalBinaryRead(reader, reader.uint32(), options, message.uint32);
                    break;
                case /* google.protobuf.Int64Value int64 */ 8:
                    message.int64 = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.int64);
                    break;
                case /* google.protobuf.UInt64Value uint64 */ 9:
                    message.uint64 = UInt64Value.internalBinaryRead(reader, reader.uint32(), options, message.uint64);
                    break;
                case /* google.protobuf.FloatValue float */ 10:
                    message.float = FloatValue.internalBinaryRead(reader, reader.uint32(), options, message.float);
                    break;
                case /* google.protobuf.DoubleValue double */ 11:
                    message.double = DoubleValue.internalBinaryRead(reader, reader.uint32(), options, message.double);
                    break;
                case /* google.protobuf.Duration duration */ 12:
                    message.duration = Duration.internalBinaryRead(reader, reader.uint32(), options, message.duration);
                    break;
                case /* google.protobuf.Timestamp timestamp */ 13:
                    message.timestamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.timestamp);
                    break;
                case /* google.protobuf.Value value */ 14:
                    message.value = Value.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                case /* google.protobuf.ListValue list */ 15:
                    message.list = ListValue.internalBinaryRead(reader, reader.uint32(), options, message.list);
                    break;
                case /* google.protobuf.Struct struct */ 16:
                    message.struct = Struct.internalBinaryRead(reader, reader.uint32(), options, message.struct);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: _ImportWellKnown, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Empty empty = 1; */
        if (message.empty)
            Empty.internalBinaryWrite(message.empty, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Any any = 2; */
        if (message.any)
            Any.internalBinaryWrite(message.any, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BytesValue bytes = 3; */
        if (message.bytes)
            BytesValue.internalBinaryWrite(message.bytes, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue bool = 4; */
        if (message.bool)
            BoolValue.internalBinaryWrite(message.bool, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue string = 5; */
        if (message.string)
            StringValue.internalBinaryWrite(message.string, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int32Value int32 = 6; */
        if (message.int32)
            Int32Value.internalBinaryWrite(message.int32, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.UInt32Value uint32 = 7; */
        if (message.uint32)
            UInt32Value.internalBinaryWrite(message.uint32, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int64Value int64 = 8; */
        if (message.int64)
            Int64Value.internalBinaryWrite(message.int64, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.UInt64Value uint64 = 9; */
        if (message.uint64)
            UInt64Value.internalBinaryWrite(message.uint64, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.FloatValue float = 10; */
        if (message.float)
            FloatValue.internalBinaryWrite(message.float, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.DoubleValue double = 11; */
        if (message.double)
            DoubleValue.internalBinaryWrite(message.double, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Duration duration = 12; */
        if (message.duration)
            Duration.internalBinaryWrite(message.duration, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp timestamp = 13; */
        if (message.timestamp)
            Timestamp.internalBinaryWrite(message.timestamp, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Value value = 14; */
        if (message.value)
            Value.internalBinaryWrite(message.value, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.ListValue list = 15; */
        if (message.list)
            ListValue.internalBinaryWrite(message.list, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Struct struct = 16; */
        if (message.struct)
            Struct.internalBinaryWrite(message.struct, writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MiLaboratories.PL._Stub._ImportWellKnown
 */
export const _ImportWellKnown = new _ImportWellKnown$Type();
