name: "minio"

services:
  service:
    image: ${MINIO_IMAGE}
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    
    ports:
      - "9001:9001"
      - "9000:9000"
    
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword

    volumes:
      - storage:/data

volumes:
  storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${MINIO_STORAGE}'
