name: "platforma-fs"

services:
  backend:
    image: ${PL_IMAGE}
    ports:
      - 6345:6345
      - 9090:9090
      - 9091:9091
    tmpfs: [ /tmp ]

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "4"

    environment:
      - "PL_API_ADDR=0.0.0.0:6345"
      - "PL_MONITORING_ENABLED=true"
      - "PL_MONITORING_ADDR=0.0.0.0:9090"
      - "PL_DEBUG_ENABLED=true"
      - "PL_DEBUG_ADDR=0.0.0.0:9091"
      - "PL_LOG_LEVEL=info"
      - "PL_LOG_DESTINATION=stdout"
      - "PL_LOG_COMMIT_SUMMARY=false"
      - "PL_LOG_RESOURCE_DATA=false"
      - "PL_AUTH_ENABLED=true"
      - "PL_DUMP_CONFIG_BEFORE_RUN=yes"
      - "PLC_FILE_PRIMARY_TYPE=FS"

    volumes:
      - primary:/storage/controllers/file/primary
      - library:/storage/controllers/file/library
      - work:/storage/controllers/file/work
      - software:/storage/controllers/runner/software
      - db:/storage/rocksdb

    restart: always

volumes:
  primary:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PL_STORAGE_PRIMARY}'

  library:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PL_STORAGE_LIBRARY}'

  work:
  software:
  db:
