name: Build NPM package
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init

    uses: milaboratory/github-ci-internal/.github/workflows/node-docker-simple-k8s.yaml@v4
    with:
      app-name: Tengo SDK
      app-name-slug: 'tengo-sdk'
      notify-telegram: true

      node-version: '20.x'
      always-auth: 'true'

      build-script-name: 'build'
      cache-version: 'v2'

      aws-iam-role-to-assume: 'arn:aws:iam::511903394050:role/milab-euce1-prod-github-oidc-role-platforma-ci-simple'
      aws-region: 'eu-central-1'
      helm-chart-atomic-upgrade: 'false'
      helm-chart-wait-timeout: '40m'

      test-pl-client-release-matrix-k8s: true
      test-pl-client-latest-k8s: true
      test-script-name: 'test'
      test-pl-major-versions: '1'
      test-pl-minor-versions: '1'

    secrets:
      env: |
        { "PL_LICENSE_VALUE": ${{ toJSON(secrets.MI_LICENSE) }} }

      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
      METADATA_DB_HOST: ${{ secrets.COUCHDB_HOST }}
      METADATA_DB_URL: ${{ secrets.COUCHDB_URL }}
      METADATA_DB_USER: ${{ secrets.COUCHDB_USER }}
      METADATA_DB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
