name: Build NPM package
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init

    uses: milaboratory/github-ci-internal/.github/workflows/node-simple-fast.yaml@v4
    with:
      app-name: Tengo Template Builder
      app-name-slug: 'tengo-template-builder'
      notify-telegram: true

      node-version: '20.x'
      is-electron-application: 'false'
      always-auth: 'true'

      build-script-name: 'build'

      test: true
      test-script-name: 'test'

    secrets:
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
