// @generated by protobuf-ts 2.11.1 with parameter client_generic,optimize_speed,generate_dependencies,force_server_none
// @generated from protobuf file "github.com/milaboratory/pl/controllers/shared/grpc/uploadapi/protocol.proto" (package "MiLaboratories.Controller.Shared", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Upload } from "./protocol";
import type { UploadAPI_Finalize_Response } from "./protocol";
import type { UploadAPI_Finalize_Request } from "./protocol";
import type { UploadAPI_UpdateProgress_Response } from "./protocol";
import type { UploadAPI_UpdateProgress_Request } from "./protocol";
import type { UploadAPI_GetPartURL_Response } from "./protocol";
import type { UploadAPI_GetPartURL_Request } from "./protocol";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { UploadAPI_Init_Response } from "./protocol";
import type { UploadAPI_Init_Request } from "./protocol";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 *
 * Upload provides access to data upload feature, allowing clients to uplad data to Platforma.
 *
 *
 * @generated from protobuf service MiLaboratories.Controller.Shared.Upload
 */
export interface IUploadClient {
    /**
     *
     * Init upload, making controller to do all required preparation steps.
     *
     *
     * @generated from protobuf rpc: Init
     */
    init(input: UploadAPI_Init_Request, options?: RpcOptions): UnaryCall<UploadAPI_Init_Request, UploadAPI_Init_Response>;
    /**
     *
     * GetPartURL provides URL for uploading chunk of the data.
     * Clients are expected to put their data directly to the given location.
     *
     *
     * @generated from protobuf rpc: GetPartURL
     */
    getPartURL(input: UploadAPI_GetPartURL_Request, options?: RpcOptions): UnaryCall<UploadAPI_GetPartURL_Request, UploadAPI_GetPartURL_Response>;
    /**
     *
     * UpdateProgress of the upload, so other clients can see how it is going.
     *
     *
     * @generated from protobuf rpc: UpdateProgress
     */
    updateProgress(input: UploadAPI_UpdateProgress_Request, options?: RpcOptions): UnaryCall<UploadAPI_UpdateProgress_Request, UploadAPI_UpdateProgress_Response>;
    /**
     *
     * Finalize informs Controller that the upload process is done.
     * Returns an error, if the total size of all uploaded chunks is not equal to
     * size of the upload given in Init.
     *
     *
     * @generated from protobuf rpc: Finalize
     */
    finalize(input: UploadAPI_Finalize_Request, options?: RpcOptions): UnaryCall<UploadAPI_Finalize_Request, UploadAPI_Finalize_Response>;
}
/**
 *
 * Upload provides access to data upload feature, allowing clients to uplad data to Platforma.
 *
 *
 * @generated from protobuf service MiLaboratories.Controller.Shared.Upload
 */
export class UploadClient implements IUploadClient, ServiceInfo {
    typeName = Upload.typeName;
    methods = Upload.methods;
    options = Upload.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     *
     * Init upload, making controller to do all required preparation steps.
     *
     *
     * @generated from protobuf rpc: Init
     */
    init(input: UploadAPI_Init_Request, options?: RpcOptions): UnaryCall<UploadAPI_Init_Request, UploadAPI_Init_Response> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadAPI_Init_Request, UploadAPI_Init_Response>("unary", this._transport, method, opt, input);
    }
    /**
     *
     * GetPartURL provides URL for uploading chunk of the data.
     * Clients are expected to put their data directly to the given location.
     *
     *
     * @generated from protobuf rpc: GetPartURL
     */
    getPartURL(input: UploadAPI_GetPartURL_Request, options?: RpcOptions): UnaryCall<UploadAPI_GetPartURL_Request, UploadAPI_GetPartURL_Response> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadAPI_GetPartURL_Request, UploadAPI_GetPartURL_Response>("unary", this._transport, method, opt, input);
    }
    /**
     *
     * UpdateProgress of the upload, so other clients can see how it is going.
     *
     *
     * @generated from protobuf rpc: UpdateProgress
     */
    updateProgress(input: UploadAPI_UpdateProgress_Request, options?: RpcOptions): UnaryCall<UploadAPI_UpdateProgress_Request, UploadAPI_UpdateProgress_Response> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadAPI_UpdateProgress_Request, UploadAPI_UpdateProgress_Response>("unary", this._transport, method, opt, input);
    }
    /**
     *
     * Finalize informs Controller that the upload process is done.
     * Returns an error, if the total size of all uploaded chunks is not equal to
     * size of the upload given in Init.
     *
     *
     * @generated from protobuf rpc: Finalize
     */
    finalize(input: UploadAPI_Finalize_Request, options?: RpcOptions): UnaryCall<UploadAPI_Finalize_Request, UploadAPI_Finalize_Response> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadAPI_Finalize_Request, UploadAPI_Finalize_Response>("unary", this._transport, method, opt, input);
    }
}
