// This file contains default values that are part of external contract from the package-builder prospective.
//
// DO NOT CHANGE THEIR VALUES UNLESS YOU KNOW WHAT YOU ARE DOING,
//
// as these values could be used in different parts of the system (i.e. tengo code, go code of backend and so on).

// Global
export const BIN_REGISTRY_NAME = 'platforma-open';
export const BIN_REGISTRY_DOWNLOAD_URL = 'https://bin.pl-open.science/';

// Python
export const PYTHON_TOOLSET = 'pip';
export const PYTHON_REQUIREMENTS_FILE = 'requirements.txt';

export const PYTHON_DOCKER_BASE_IMAGE = 'python:3.12-slim';

// Conda
export const CONDA_MICROMAMBA_VERSION = '2.3.2-0';
export const CONDA_SOURCE_ENV_SPEC_FILE = 'conda-spec.yaml'; // inside git repo: what env to build in CI
export const CONDA_FROZEN_ENV_SPEC_FILE = 'frozen-spec.yaml'; // inside built package: how to restore env on backend side
export const CONDA_DATA_LOCATION = 'conda-env-data'; // inside built package: where MICROMAMBA_ROOT_PREFIX should point on backend side

export const CONDA_DOCKER_BASE_IMAGE = 'ubuntu:22.04';

// Docker
export const DOCKER_REGISTRY = 'containers.pl-open.science/milaboratories/pl-containers';
export const DOCKER_DOCKERFILE = 'Dockerfile'; // inside git repo: path to Dockerfile to build by default
export const DOCKER_PLACEHOLDER_PKG = '/app'; // {pkg} placeholder value to by used in 'cmd' (for autogenerated docker images)
