// DO NOT EDIT. This file was generated by oclif-index utility.

import Cmd0 from "./commands/build";
import Cmd1 from "./commands/prepublish";
import Cmd2 from "./commands/build/all";
import Cmd3 from "./commands/build/docker";
import Cmd4 from "./commands/build/packages";
import Cmd5 from "./commands/publish/all";
import Cmd6 from "./commands/publish/docker";
import Cmd7 from "./commands/publish/packages";

export const COMMANDS = {
  build: Cmd0,
  prepublish: Cmd1,
  "build:all": Cmd2,
  "build:docker": Cmd3,
  "build:packages": Cmd4,
  "publish:all": Cmd5,
  "publish:docker": Cmd6,
  "publish:packages": Cmd7,
};
