// DO NOT EDIT. This file was generated by oclif-index utility.

import Cmd0 from './commands/build';
import Cmd1 from './commands/publish';
import Cmd2 from './commands/sign';
import Cmd3 from './commands/build/descriptors';
import Cmd4 from './commands/build/packages';
import Cmd5 from './commands/publish/descriptors';
import Cmd6 from './commands/publish/packages';
import Cmd7 from './commands/sign/packages';
import Cmd8 from './commands/get/package/name';
import Cmd9 from './commands/get/package/path';
import Cmd10 from './commands/get/package/version';

// prettier-ignore
export const COMMANDS = {
  'build': Cmd0,
  'publish': Cmd1,
  'sign': Cmd2,
  'build:descriptors': Cmd3,
  'build:packages': Cmd4,
  'publish:descriptors': Cmd5,
  'publish:packages': Cmd6,
  'sign:packages': Cmd7,
  'get:package:name': Cmd8,
  'get:package:path': Cmd9,
  'get:package:version': Cmd10
};
