// DO NOT EDIT. This file was generated by oclif-index utility.

import Cmd0 from './commands/build';
import Cmd1 from './commands/prepublish';
import Cmd2 from './commands/sign';
import Cmd3 from './commands/build/all';
import Cmd4 from './commands/build/docker';
import Cmd5 from './commands/build/packages';
import Cmd6 from './commands/publish/all';
import Cmd7 from './commands/publish/docker';
import Cmd8 from './commands/publish/packages';

// prettier-ignore
export const COMMANDS = {
  'build': Cmd0,
  'prepublish': Cmd1,
  'sign': Cmd2,
  'build:all': Cmd3,
  'build:docker': Cmd4,
  'build:packages': Cmd5,
  'publish:all': Cmd6,
  'publish:docker': Cmd7,
  'publish:packages': Cmd8,
};
