// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ApiController = {
    type?: string;
    id?: string;
    subscriptionID?: string;
};

export type ApiControllerApiCreateRequest = {
    id?: string;
    controllerType?: string;
};

export type ApiControllerApiCreateResponse = {
    controllerId?: string;
};

export type ApiControllerApiExistsRequest = {
    controllerType?: string;
};

export type ApiControllerApiExistsResponse = {
    exists?: boolean;
};

export type ApiControllerApiGetRequest = {
    controllerType?: string;
};

export type ApiControllerApiGetResponse = {
    controller?: ApiController;
};

export type ApiControllerApiUpdateRequest = {
    controllerType?: string;
    filters?: {
        [key: string]: RTypesNotificationFilter;
    };
    resourceSchemas?: Array<ApiResourceSchema>;
};

export type ApiControllerApiUpdateResponse = {
    [key: string]: unknown;
};

export type ApiControllerKvapiGetFlagRequest = {
    controllerType?: string;
    key?: string;
};

export type ApiControllerKvapiGetFlagResponse = {
    value?: boolean;
};

export type ApiControllerKvapiGetIfExistsRequest = {
    controllerType?: string;
    key?: string;
};

export type ApiControllerKvapiGetIfExistsResponse = {
    value?: string;
    exists?: boolean;
};

export type ApiControllerKvapiGetRequest = {
    controllerType?: string;
    key?: string;
};

export type ApiControllerKvapiGetResponse = {
    value?: string;
};

export type ApiControllerKvapiSetFlagRequest = {
    controllerType?: string;
    key?: string;
    value?: boolean;
};

export type ApiControllerKvapiSetFlagResponse = {
    [key: string]: unknown;
};

export type ApiControllerKvapiSetRequest = {
    controllerType?: string;
    key?: string;
    value?: string;
};

export type ApiControllerKvapiSetResponse = {
    [key: string]: unknown;
};

export type ApiField = {
    id?: BaseFieldRef;
    type?: BaseFieldType;
    features?: ResourceFeatures;
    /**
     * _resolved_ value of field or _assigned_ if the field was assigned to a resource.
     * If field refers to another field, it will get
     * value only when this chain of references ends up with direct resource
     * reference. At that moment all fields in the chain will get their values
     * resolved and will start to refer to the same resource directly.
     */
    value?: string;
    valueStatus?: FieldValueStatus;
    /**
     * If the value is in its final state (ready, duplicate or error)
     */
    valueIsFinal?: boolean;
    /**
     * Resource error resource id if any.
     * Is intended to report problems _from_ platform to client.
     */
    error?: string;
};

export type ApiFieldApiCreateRequest = {
    type?: BaseFieldType;
    id?: BaseFieldRef;
};

export type ApiFieldApiCreateResponse = {
    globalId?: BaseFieldRef;
};

export type ApiFieldApiExistsRequest = {
    field?: BaseFieldRef;
};

export type ApiFieldApiExistsResponse = {
    exists?: boolean;
};

export type ApiFieldApiGetRequest = {
    field?: BaseFieldRef;
};

export type ApiFieldApiGetResponse = {
    field?: ApiField;
};

export type ApiFieldApiListRequest = {
    resourceId?: string;
    /**
     * Start the listing from given position, returning first field with
     * name >= start_from.
     */
    startFrom?: string;
    /**
     * Non-zero value makes API to limit number of returned fields to at
     * most <limit>.
     * Zero value makes API to return all available fields of the resource.
     */
    limit?: number;
};

/**
 * Multi-message
 */
export type ApiFieldApiListResponse = {
    field?: ApiField;
    /**
     * The name of field next to the current one.
     *
     * Is not empty only for the last message in the current listing, when <limit> was > 0 in List.Request AND
     * there is more items to read (the listing was stopped because of that limit)
     *
     * Use <next> value as <start_from> in the List.Request to continue listing.
     */
    next?: string;
};

export type ApiFieldApiRemoveRequest = {
    field?: BaseFieldRef;
};

export type ApiFieldApiRemoveResponse = {
    [key: string]: unknown;
};

export type ApiFieldApiSetErrorRequest = {
    field?: BaseFieldRef;
    errResourceId?: string;
};

export type ApiFieldApiSetErrorResponse = {
    [key: string]: unknown;
};

export type ApiFieldApiSetRequest = {
    field?: BaseFieldRef;
    value?: BaseFieldRef;
};

export type ApiFieldApiSetResponse = {
    [key: string]: unknown;
};

export type ApiFieldSchema = {
    type?: BaseFieldType;
    name?: string;
};

export type ApiNotification = {
    subscriptionId?: string;
    eventId?: string;
    resourceId?: string;
    resourceType?: BaseResourceType;
    events?: NotificationEvents;
    fieldChanges?: {
        [key: string]: NotificationFieldChange;
    };
    payload?: NotificationFilterPayload;
    filterName?: string;
    txSpan?: ApiSpanInfo;
};

export type ApiNotificationApiDiscardRequest = {
    subscriptionId?: string;
    eventId?: string;
};

export type ApiNotificationApiDiscardResponse = {
    [key: string]: unknown;
};

export type ApiNotificationApiGetRequest = {
    subscription?: string;
    maxNotifications?: number;
};

export type ApiNotificationApiGetResponse = {
    notifications?: Array<ApiNotification>;
};

export type ApiResource = {
    id?: string;
    /**
     * could be empty, it depends on resource lifecycle state
     */
    canonicalId?: string;
    kind?: ResourceKind;
    type?: BaseResourceType;
    data?: string;
    features?: ResourceFeatures;
    fields?: Array<ApiField>;
    /**
     * Resource has at least one field with error
     */
    hasErrors?: boolean;
    inputsLocked?: boolean;
    outputsLocked?: boolean;
    resourceReady?: boolean;
    isFinal?: boolean;
    originalResourceId?: string;
    parentResourceId?: string;
    createdTime?: string;
    deletedTime?: string;
};

export type ApiResourceApiExistsRequest = {
    resourceId?: string;
};

export type ApiResourceApiExistsResponse = {
    exists?: boolean;
};

export type ApiResourceApiFeature = {
    controllerType?: string;
    featureName?: string;
    resourceType?: BaseResourceType;
    endpoint?: string;
};

export type ApiResourceApiGetRequest = {
    resourceId?: string;
    loadFields?: boolean;
};

export type ApiResourceApiGetResponse = {
    resource?: ApiResource;
};

export type ApiResourceApiRemoveRequest = {
    id?: string;
};

export type ApiResourceApiRemoveResponse = {
    [key: string]: unknown;
};

export type ApiResourceApiSetErrorRequest = {
    resourceId?: string;
    errorResourceId?: string;
};

export type ApiResourceApiSetErrorResponse = {
    [key: string]: unknown;
};

export type ApiResourceKvapiDeleteRequest = {
    resourceId?: string;
    key?: string;
};

export type ApiResourceKvapiDeleteResponse = {
    [key: string]: unknown;
};

export type ApiResourceKvapiGetFlagRequest = {
    resourceId?: string;
    key?: string;
};

export type ApiResourceKvapiGetFlagResponse = {
    value?: boolean;
};

export type ApiResourceKvapiGetIfExistsRequest = {
    resourceId?: string;
    key?: string;
};

export type ApiResourceKvapiGetIfExistsResponse = {
    value?: string;
    exists?: boolean;
};

export type ApiResourceKvapiGetRequest = {
    resourceId?: string;
    key?: string;
};

export type ApiResourceKvapiGetResponse = {
    value?: string;
};

export type ApiResourceKvapiListRequest = {
    resourceId?: string;
    /**
     * Start the listing from given position, returning first item with
     * key >= start_from.
     */
    startFrom?: string;
    /**
     * Non-zero value makes API to limit its responses count to at most
     * <limit> number of items.
     * Zero value makes API to return all available items.
     */
    limit?: number;
};

/**
 * Multi-message
 */
export type ApiResourceKvapiListResponse = {
    record?: ResponseKv;
    /**
     * The key of the KV item next to the last returned item.
     *
     * Is not empty only for the last message in the current listing, when <limit> was > 0 in List.Request AND
     * there is more items to read (the listing was stopped because of that limit)
     *
     * Use <next> value as <start_from> of the List.Request to continue listing.
     */
    next?: string;
};

export type ApiResourceKvapiSetFlagRequest = {
    resourceId?: string;
    key?: string;
    value?: boolean;
};

export type ApiResourceKvapiSetFlagResponse = {
    [key: string]: unknown;
};

export type ApiResourceKvapiSetRequest = {
    resourceId?: string;
    key?: string;
    value?: string;
};

export type ApiResourceKvapiSetResponse = {
    [key: string]: unknown;
};

export type ApiResourceSchema = {
    type?: BaseResourceType;
    fields?: Array<ApiFieldSchema>;
};

export type ApiSpanInfo = {
    path?: string;
    carrier?: {
        [key: string]: string;
    };
};

export type ApiTxApiDiscardRequest = {
    [key: string]: unknown;
};

export type ApiTxApiDiscardResponse = {
    [key: string]: unknown;
};

export type AuthApiGetJwtTokenRequest = {
    expiration?: string;
};

export type AuthApiGetJwtTokenResponse = {
    token?: string;
};

export type AuthApiListMethodsResponse = {
    methods?: Array<ListMethodsMethodInfo>;
};

export type BaseFieldRef = {
    resourceId?: string;
    fieldName?: string;
};

export type BaseFieldType = 'INVALID' | 'INPUT' | 'OUTPUT' | 'SERVICE' | 'ONE_TIME_WRITABLE' | 'DYNAMIC' | 'MULTIPLE_TIMES_WRITABLE';

export type BaseResourceType = {
    name?: string;
    version?: string;
};

export type CacheApiDeleteExpiredRecordsRequest = {
    [key: string]: unknown;
};

export type CacheApiDeleteExpiredRecordsResponse = {
    [key: string]: unknown;
};

export type CacheApiSetToFieldRequest = {
    id?: BaseFieldRef;
    period?: string;
};

export type CacheApiSetToFieldResponse = {
    [key: string]: unknown;
};

export type ControllerApiAttachSubscriptionRequest = {
    controllerId?: string;
    subscriptionId?: string;
};

export type ControllerApiAttachSubscriptionResponse = {
    [key: string]: unknown;
};

export type ControllerApiClearFeaturesRequest = {
    controllerType?: string;
};

export type ControllerApiClearFeaturesResponse = {
    [key: string]: unknown;
};

export type ControllerApiDeregisterRequest = {
    controllerType?: string;
};

export type ControllerApiDeregisterResponse = {
    [key: string]: unknown;
};

export type ControllerApiGetNotificationsRequest = {
    controllerType?: string;
    maxNotifications?: number;
};

export type ControllerApiGetNotificationsResponse = {
    notifications?: Array<ApiNotification>;
};

export type ControllerApiGetUrlRequest = {
    controllerAlias?: string;
    resourceId?: string;
};

export type ControllerApiGetUrlResponse = {
    controllerUrl?: string;
};

export type ControllerApiRegisterRequest = {
    controllerType?: string;
    filters?: {
        [key: string]: RTypesNotificationFilter;
    };
    resourceSchemas?: Array<ApiResourceSchema>;
};

export type ControllerApiRegisterResponse = {
    controllerId?: string;
    subscriptionId?: string;
};

export type ControllerApiRemoveAliasesAndUrlsRequest = {
    controllerType?: string;
};

export type ControllerApiRemoveAliasesAndUrlsResponse = {
    [key: string]: unknown;
};

export type ControllerApiSetFeaturesRequest = {
    features?: Array<ApiResourceApiFeature>;
};

export type ControllerApiSetFeaturesResponse = {
    [key: string]: unknown;
};

export type ControllerApiWriteAliasesAndUrlsRequest = {
    controllerType?: string;
    aliasesToUrls?: {
        [key: string]: string;
    };
};

export type ControllerApiWriteAliasesAndUrlsResponse = {
    [key: string]: unknown;
};

export type ControllerKvapiGetFlagIfExistsRequest = {
    controllerType?: string;
    key?: string;
};

export type ControllerKvapiGetFlagIfExistsResponse = {
    value?: boolean;
    exists?: boolean;
};

export type FieldApiResetRequest = {
    field?: BaseFieldRef;
};

export type FieldApiResetResponse = {
    [key: string]: unknown;
};

export type FieldValueStatus = 'INVALID' | 'EMPTY' | 'ASSIGNED' | 'RESOLVED';

export type LeaseReleaseRequest = {
    resourceId?: string;
    leaseId?: string;
};

export type LeaseReleaseResponse = {
    [key: string]: unknown;
};

export type ListByTypeRequest = {
    resourceType?: BaseResourceType;
    /**
     * Non-zero value makes API to limit its responses count to at most
     * <limit> number of items.
     * Zero value makes API to return all available items.
     */
    limit?: number;
    /**
     * Start listing from given resource ID (not including this resource ID itself)
     * After == 100 means listing will NOT contain resources with ID = 100 and lower.
     */
    after?: string;
    /**
     * True value makes API to return original resources instead of duplicates.
     */
    resolveDuplicates?: boolean;
    /**
     * Load fields for each resource in list.
     */
    loadFields?: boolean;
};

/**
 * Multi-message
 */
export type ListByTypeResponse = {
    resource?: ApiResource;
};

export type ListMethodsMethodInfo = {
    type?: string;
    name?: string;
    info?: {
        [key: string]: string;
    };
};

export type LocksApiLeaseCreateRequest = {
    resourceId?: string;
    timeout?: string;
    name?: string;
};

export type LocksApiLeaseCreateResponse = {
    leaseId?: string;
};

export type LocksApiLeaseUpdateRequest = {
    resourceId?: string;
    leaseId?: string;
    timeout?: string;
    name?: string;
};

export type LocksApiLeaseUpdateResponse = {
    [key: string]: unknown;
};

export type MaintenanceApiLicenseResponse = {
    /**
     * HTTP status code of the last valid response from license server.
     */
    status?: number;
    /**
     * true if status is 200
     */
    isOk?: boolean;
    /**
     * Raw response body as it was received from the license server.
     */
    responseBody?: string;
};

export type MaintenanceApiPingResponse = {
    coreVersion?: string;
    coreFullVersion?: string;
    serverInfo?: string;
    compression?: ResponseCompression;
    /**
     * instanceID is a unique ID that changes when we reset DB state.
     * If we reset a state and a database, but the address of the backend is still the same,
     * without instanceID we are not sure if it's the same state or not,
     * and UI can't detect it and clear its state (e.g. caches of drivers).
     */
    instanceId?: string;
    /**
     * <os>-<arch>
     */
    platform?: string;
    /**
     * linux / windows / macosx
     */
    os?: string;
    /**
     * x64 / aarch64
     */
    arch?: string;
};

export type MiscApiListResourceTypesResponse = {
    types?: Array<BaseResourceType>;
};

export type NotificationApiAckRequest = {
    subscriptionId?: string;
    eventId?: string;
};

export type NotificationApiAckResponse = {
    [key: string]: unknown;
};

export type NotificationEvents = {
    resourceCreated?: boolean;
    resourceDeleted?: boolean;
    resourceReady?: boolean;
    resourceDuplicate?: boolean;
    resourceError?: boolean;
    inputsLocked?: boolean;
    outputsLocked?: boolean;
    fieldCreated?: boolean;
    fieldGotError?: boolean;
    inputSet?: boolean;
    allInputsSet?: boolean;
    outputSet?: boolean;
    allOutputsSet?: boolean;
    genericOtwSet?: boolean;
    dynamicChanged?: boolean;
};

export type NotificationFieldChange = {
    old?: ApiField;
    new?: ApiField;
};

export type NotificationFilterEventFilter = {
    all?: boolean;
    resourceCreated?: boolean;
    resourceDeleted?: boolean;
    resourceReady?: boolean;
    resourceDuplicate?: boolean;
    resourceError?: boolean;
    /**
     * Field events
     */
    inputsLocked?: boolean;
    outputsLocked?: boolean;
    fieldCreated?: boolean;
    fieldGotError?: boolean;
    inputSet?: boolean;
    allInputsSet?: boolean;
    outputSet?: boolean;
    allOutputsSet?: boolean;
    genericOtwSet?: boolean;
    dynamicChanged?: boolean;
};

export type NotificationFilterPayload = {
    values?: {
        [key: string]: string;
    };
};

export type PlapiTx = {
    isValid?: boolean;
    id?: string;
};

export type RTypesNotificationFilter = {
    resourceType?: BaseResourceType;
    resourceId?: string;
    eventFilter?: NotificationFilterEventFilter;
    payload?: NotificationFilterPayload;
};

export type RequestWritableTx = 'INVALID' | 'WRITABLE' | 'NOT_WRITABLE';

export type ResourceApiCreateChildRequest = {
    id?: string;
    type?: BaseResourceType;
    parentField?: BaseFieldRef;
};

export type ResourceApiCreateChildResponse = {
    resourceId?: string;
};

export type ResourceApiCreateEphemeralRequest = {
    id?: string;
    type?: BaseResourceType;
    data?: string;
};

export type ResourceApiCreateEphemeralResponse = {
    resourceId?: string;
};

export type ResourceApiCreateRootRequest = {
    id?: string;
    type?: BaseResourceType;
};

export type ResourceApiCreateRootResponse = {
    resourceId?: string;
};

export type ResourceApiCreateSingletonRequest = {
    id?: string;
    type?: BaseResourceType;
    data?: string;
    errorIfExists?: boolean;
};

export type ResourceApiCreateSingletonResponse = {
    resourceId?: string;
};

export type ResourceApiCreateStructRequest = {
    id?: string;
    type?: BaseResourceType;
    data?: string;
};

export type ResourceApiCreateStructResponse = {
    resourceId?: string;
};

export type ResourceApiCreateValueRequest = {
    id?: string;
    type?: BaseResourceType;
    data?: string;
    errorIfExists?: boolean;
};

export type ResourceApiCreateValueResponse = {
    resourceId?: string;
};

export type ResourceApiGetSingletonRequest = {
    type?: BaseResourceType;
    data?: string;
    loadFields?: boolean;
};

export type ResourceApiGetSingletonResponse = {
    resource?: ApiResource;
};

export type ResourceApiGetValueIdRequest = {
    type?: BaseResourceType;
    data?: string;
};

export type ResourceApiGetValueIdResponse = {
    resourceId?: string;
};

export type ResourceApiLockInputsRequest = {
    resourceId?: string;
};

export type ResourceApiLockInputsResponse = {
    [key: string]: unknown;
};

export type ResourceApiLockOutputsRequest = {
    resourceId?: string;
};

export type ResourceApiLockOutputsResponse = {
    [key: string]: unknown;
};

export type ResourceApiNameDeleteRequest = {
    name?: string;
};

export type ResourceApiNameDeleteResponse = {
    [key: string]: unknown;
};

export type ResourceApiNameExistsRequest = {
    name?: string;
};

export type ResourceApiNameExistsResponse = {
    exists?: boolean;
};

export type ResourceApiNameGetRequest = {
    name?: string;
};

export type ResourceApiNameGetResponse = {
    resourceId?: string;
};

export type ResourceApiNameSetRequest = {
    resourceId?: string;
    name?: string;
};

export type ResourceApiNameSetResponse = {
    [key: string]: unknown;
};

export type ResourceApiTreeRequest = {
    resourceId?: string;
    /**
     * Limit maximum depth the tree is traversed.
     * The resource <resource_id> is considered on depth = 0, the values of its fiels
     * are on depth = 1 and so on.
     * The maximum uint32 value disables the limit at all.
     * 0 value makes API to return only single resource <resource_id> and is actually
     * equal to Get.Request
     */
    maxDepth?: number;
};

/**
 * Multi-message
 */
export type ResourceApiTreeResponse = {
    resource?: ApiResource;
};

export type ResourceApiTreeSizeRequest = {
    resourceId?: string;
};

export type ResourceApiTreeSizeResponse = {
    /**
     * size of all tree resources in bytes
     * could change between call regarding compression algorithm
     */
    size?: string;
    resourceCount?: string;
};

export type ResourceFeatures = {
    /**
     * false = 'supports deduplication'
     */
    ephemeral?: boolean;
};

export type ResourceKind = 'KIND_INVALID' | 'KIND_STRUCTURAL' | 'KIND_VALUE';

export type ResponseCompression = 'NONE' | 'GZIP';

export type ResponseKv = {
    key?: string;
    value?: string;
};

export type ServerMessageMulti = {
    /**
     * Sequential message ID for multi-message response, starting from 1.
     * Caller can use 'id > 0' check as a sign of multi-message response.
     * Some API requests produce several messages in response by design (say, listings)
     * In that case, the server responses to the client with many messages, each having
     * the same <request_id> value and different <message_id> values.
     */
    id?: number;
    /**
     * Sign of the last message in multi-message response.
     * Helps to wrap multi-message responses into iterators on client side.
     */
    isLast?: boolean;
    /**
     * Sign of empty multi-message response. Some multi-message responses can produce nothing
     * (like listing of empty directory). In that case client still has to know that the request was
     * handled and the empty result is OK.
     */
    isEmpty?: boolean;
};

export type SubscriptionApiAttachFilterRequest = {
    subscriptionId?: string;
    filterName?: string;
    filterId?: string;
};

export type SubscriptionApiAttachFilterResponse = {
    [key: string]: unknown;
};

export type SubscriptionApiCreateFilterRequest = {
    id?: string;
    filter?: RTypesNotificationFilter;
};

export type SubscriptionApiCreateFilterResponse = {
    filterId?: string;
};

export type SubscriptionApiCreateSubscriptionRequest = {
    id?: string;
    blocking?: boolean;
    gc?: boolean;
};

export type SubscriptionApiCreateSubscriptionResponse = {
    subscriptionId?: string;
};

export type SubscriptionApiDetachFilterRequest = {
    subscriptionId?: string;
    filterName?: string;
};

export type SubscriptionApiDetachFilterResponse = {
    [key: string]: unknown;
};

export type TxApiCommitRequest = {
    [key: string]: unknown;
};

export type TxApiCommitResponse = {
    success?: boolean;
};

export type TxApiOpenRequest = {
    name?: string;
    writable?: RequestWritableTx;
    enableFormattedErrors?: boolean;
};

export type TxApiOpenResponse = {
    tx?: PlapiTx;
};

export type TxApiServerMessage = {
    requestId?: number;
    multiMessage?: ServerMessageMulti;
    txOpen?: TxApiOpenResponse;
    txCommit?: TxApiCommitResponse;
    txDiscard?: ApiTxApiDiscardResponse;
    resourceCreateRoot?: ResourceApiCreateRootResponse;
    resourceRemove?: ApiResourceApiRemoveResponse;
    resourceCreateStruct?: ResourceApiCreateStructResponse;
    resourceCreateEphemeral?: ResourceApiCreateEphemeralResponse;
    resourceCreateValue?: ResourceApiCreateValueResponse;
    resourceGetValueId?: ResourceApiGetValueIdResponse;
    resourceCreateSingleton?: ResourceApiCreateSingletonResponse;
    resourceGetSingleton?: ResourceApiGetSingletonResponse;
    resourceCreateChild?: ResourceApiCreateChildResponse;
    resourceLockInputs?: ResourceApiLockInputsResponse;
    resourceLockOutputs?: ResourceApiLockOutputsResponse;
    resourceExists?: ApiResourceApiExistsResponse;
    resourceGet?: ApiResourceApiGetResponse;
    resourceSetError?: ApiResourceApiSetErrorResponse;
    resourceListByType?: ListByTypeResponse;
    resourceNameSet?: ResourceApiNameSetResponse;
    resourceNameGet?: ResourceApiNameGetResponse;
    resourceNameExists?: ResourceApiNameExistsResponse;
    resourceNameDelete?: ResourceApiNameDeleteResponse;
    resourceTree?: ResourceApiTreeResponse;
    resourceTreeSize?: ResourceApiTreeSizeResponse;
    fieldCreate?: ApiFieldApiCreateResponse;
    fieldExists?: ApiFieldApiExistsResponse;
    fieldSet?: ApiFieldApiSetResponse;
    fieldSetError?: ApiFieldApiSetErrorResponse;
    fieldGet?: ApiFieldApiGetResponse;
    fieldReset?: FieldApiResetResponse;
    fieldRemove?: ApiFieldApiRemoveResponse;
    fieldList?: ApiFieldApiListResponse;
    subscriptionCreate?: SubscriptionApiCreateSubscriptionResponse;
    subscriptionCreateFilter?: SubscriptionApiCreateFilterResponse;
    subscriptionAttachFilter?: SubscriptionApiAttachFilterResponse;
    subscriptionDetachFilter?: SubscriptionApiDetachFilterResponse;
    notificationGet?: ApiNotificationApiGetResponse;
    notificationAck?: NotificationApiAckResponse;
    notificationDiscard?: ApiNotificationApiDiscardResponse;
    resourceKeyValueSet?: ApiResourceKvapiSetResponse;
    resourceKeyValueGet?: ApiResourceKvapiGetResponse;
    resourceKeyValueGetIfExists?: ApiResourceKvapiGetIfExistsResponse;
    resourceKeyValueSetFlag?: ApiResourceKvapiSetFlagResponse;
    resourceKeyValueGetFlag?: ApiResourceKvapiGetFlagResponse;
    resourceKeyValueGetFlagIfExists?: ApiResourceKvapiGetFlagResponse;
    resourceKeyValueDelete?: ApiResourceKvapiDeleteResponse;
    resourceKeyValueList?: ApiResourceKvapiListResponse;
    controllerKeyValueSet?: ApiControllerKvapiSetResponse;
    controllerKeyValueGet?: ApiControllerKvapiGetResponse;
    controllerKeyValueGetIfExists?: ApiControllerKvapiGetIfExistsResponse;
    controllerKeyValueSetFlag?: ApiControllerKvapiSetFlagResponse;
    controllerKeyValueGetFlag?: ApiControllerKvapiGetFlagResponse;
    controllerKeyValueGetFlagIfExists?: ControllerKvapiGetFlagIfExistsResponse;
    cacheSetToField?: CacheApiSetToFieldResponse;
    cacheDeleteExpiredRecords?: CacheApiDeleteExpiredRecordsResponse;
    controllerFeaturesSet?: ControllerApiSetFeaturesResponse;
    controllerFeaturesClear?: ControllerApiClearFeaturesResponse;
    error?: RpcStatus;
};

export type TxApiSyncResponse = {
    [key: string]: unknown;
};

/**
 * `Any` contains an arbitrary serialized protocol buffer message along with a
 * URL that describes the type of the serialized message.
 *
 * Protobuf library provides support to pack/unpack Any values in the form
 * of utility functions or additional generated methods of the Any type.
 *
 * Example 1: Pack and unpack a message in C++.
 *
 * Foo foo = ...;
 * Any any;
 * any.PackFrom(foo);
 * ...
 * if (any.UnpackTo(&foo)) {
 * ...
 * }
 *
 * Example 2: Pack and unpack a message in Java.
 *
 * Foo foo = ...;
 * Any any = Any.pack(foo);
 * ...
 * if (any.is(Foo.class)) {
 * foo = any.unpack(Foo.class);
 * }
 * // or ...
 * if (any.isSameTypeAs(Foo.getDefaultInstance())) {
 * foo = any.unpack(Foo.getDefaultInstance());
 * }
 *
 * Example 3: Pack and unpack a message in Python.
 *
 * foo = Foo(...)
 * any = Any()
 * any.Pack(foo)
 * ...
 * if any.Is(Foo.DESCRIPTOR):
 * any.Unpack(foo)
 * ...
 *
 * Example 4: Pack and unpack a message in Go
 *
 * foo := &pb.Foo{...}
 * any, err := anypb.New(foo)
 * if err != nil {
 * ...
 * }
 * ...
 * foo := &pb.Foo{}
 * if err := any.UnmarshalTo(foo); err != nil {
 * ...
 * }
 *
 * The pack methods provided by protobuf library will by default use
 * 'type.googleapis.com/full.type.name' as the type URL and the unpack
 * methods only use the fully qualified type name after the last '/'
 * in the type URL, for example "foo.bar.com/x/y.z" will yield type
 * name "y.z".
 *
 * JSON
 * ====
 * The JSON representation of an `Any` value uses the regular
 * representation of the deserialized, embedded message, with an
 * additional field `@type` which contains the type URL. Example:
 *
 * package google.profile;
 * message Person {
 * string first_name = 1;
 * string last_name = 2;
 * }
 *
 * {
 * "@type": "type.googleapis.com/google.profile.Person",
 * "firstName": <string>,
 * "lastName": <string>
 * }
 *
 * If the embedded message type is well-known and has a custom JSON
 * representation, that representation will be embedded adding a field
 * `value` which holds the custom JSON in addition to the `@type`
 * field. Example (for message [google.protobuf.Duration][]):
 *
 * {
 * "@type": "type.googleapis.com/google.protobuf.Duration",
 * "value": "1.212s"
 * }
 */
export type ProtobufAny = {
    /**
     * A URL/resource name that uniquely identifies the type of the serialized
     * protocol buffer message. This string must contain at least
     * one "/" character. The last segment of the URL's path must represent
     * the fully qualified name of the type (as in
     * `path/google.protobuf.Duration`). The name should be in a canonical form
     * (e.g., leading "." is not accepted).
     *
     * In practice, teams usually precompile into the binary all types that they
     * expect it to use in the context of Any. However, for URLs which use the
     * scheme `http`, `https`, or no scheme, one can optionally set up a type
     * server that maps type URLs to message definitions as follows:
     *
     * * If no scheme is provided, `https` is assumed.
     * * An HTTP GET on the URL must yield a [google.protobuf.Type][]
     * value in binary format, or produce an error.
     * * Applications are allowed to cache lookup results based on the
     * URL, or have them precompiled into a binary to avoid any
     * lookup. Therefore, binary compatibility needs to be preserved
     * on changes to types. (Use versioned type names to manage
     * breaking changes.)
     *
     * Note: this functionality is not currently available in the official
     * protobuf release, and it is not used for type URLs beginning with
     * type.googleapis.com. As of May 2023, there are no widely used type server
     * implementations and no plans to implement one.
     *
     * Schemes other than `http`, `https` (or the empty scheme) might be
     * used with implementation specific semantics.
     */
    '@type'?: string;
    [key: string]: unknown | string | undefined;
};

/**
 * The `Status` type defines a logical error model that is suitable for
 * different programming environments, including REST APIs and RPC APIs. It is
 * used by [gRPC](https://github.com/grpc). Each `Status` message contains
 * three pieces of data: error code, error message, and error details.
 *
 * You can find out more about this error model and how to work with it in the
 * [API Design Guide](https://cloud.google.com/apis/design/errors).
 */
export type RpcStatus = {
    /**
     * The status code, which should be an enum value of
     * [google.rpc.Code][google.rpc.Code].
     */
    code?: number;
    /**
     * A developer-facing error message, which should be in English. Any
     * user-facing error message should be localized and sent in the
     * [google.rpc.Status.details][google.rpc.Status.details] field, or localized
     * by the client.
     */
    message?: string;
    /**
     * A list of messages that carry the error details.  There is a common set of
     * message types for APIs to use.
     */
    details?: Array<ProtobufAny>;
};

export type PlatformGetJwtTokenData = {
    body: AuthApiGetJwtTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/jwt-token';
};

export type PlatformGetJwtTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformGetJwtTokenError = PlatformGetJwtTokenErrors[keyof PlatformGetJwtTokenErrors];

export type PlatformGetJwtTokenResponses = {
    /**
     * A successful response.
     */
    200: AuthApiGetJwtTokenResponse;
};

export type PlatformGetJwtTokenResponse = PlatformGetJwtTokenResponses[keyof PlatformGetJwtTokenResponses];

export type PlatformAuthMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/methods';
};

export type PlatformAuthMethodsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformAuthMethodsError = PlatformAuthMethodsErrors[keyof PlatformAuthMethodsErrors];

export type PlatformAuthMethodsResponses = {
    /**
     * A successful response.
     */
    200: AuthApiListMethodsResponse;
};

export type PlatformAuthMethodsResponse = PlatformAuthMethodsResponses[keyof PlatformAuthMethodsResponses];

export type PlatformRemoveControllerAliasesAndUrlsData = {
    body: ControllerApiRemoveAliasesAndUrlsRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/aliases-and-urls';
};

export type PlatformRemoveControllerAliasesAndUrlsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformRemoveControllerAliasesAndUrlsError = PlatformRemoveControllerAliasesAndUrlsErrors[keyof PlatformRemoveControllerAliasesAndUrlsErrors];

export type PlatformRemoveControllerAliasesAndUrlsResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiRemoveAliasesAndUrlsResponse;
};

export type PlatformRemoveControllerAliasesAndUrlsResponse = PlatformRemoveControllerAliasesAndUrlsResponses[keyof PlatformRemoveControllerAliasesAndUrlsResponses];

export type PlatformWriteControllerAliasesAndUrlsData = {
    body: ControllerApiWriteAliasesAndUrlsRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/aliases-and-urls';
};

export type PlatformWriteControllerAliasesAndUrlsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformWriteControllerAliasesAndUrlsError = PlatformWriteControllerAliasesAndUrlsErrors[keyof PlatformWriteControllerAliasesAndUrlsErrors];

export type PlatformWriteControllerAliasesAndUrlsResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiWriteAliasesAndUrlsResponse;
};

export type PlatformWriteControllerAliasesAndUrlsResponse = PlatformWriteControllerAliasesAndUrlsResponses[keyof PlatformWriteControllerAliasesAndUrlsResponses];

export type PlatformControllerAttachSubscriptionData = {
    body: ControllerApiAttachSubscriptionRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/attach-subscription';
};

export type PlatformControllerAttachSubscriptionErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerAttachSubscriptionError = PlatformControllerAttachSubscriptionErrors[keyof PlatformControllerAttachSubscriptionErrors];

export type PlatformControllerAttachSubscriptionResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiAttachSubscriptionResponse;
};

export type PlatformControllerAttachSubscriptionResponse = PlatformControllerAttachSubscriptionResponses[keyof PlatformControllerAttachSubscriptionResponses];

export type PlatformControllerCreateData = {
    body: ApiControllerApiCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/create';
};

export type PlatformControllerCreateErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerCreateError = PlatformControllerCreateErrors[keyof PlatformControllerCreateErrors];

export type PlatformControllerCreateResponses = {
    /**
     * A successful response.
     */
    200: ApiControllerApiCreateResponse;
};

export type PlatformControllerCreateResponse = PlatformControllerCreateResponses[keyof PlatformControllerCreateResponses];

export type PlatformControllerDeregisterData = {
    body: ControllerApiDeregisterRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/deregister';
};

export type PlatformControllerDeregisterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerDeregisterError = PlatformControllerDeregisterErrors[keyof PlatformControllerDeregisterErrors];

export type PlatformControllerDeregisterResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiDeregisterResponse;
};

export type PlatformControllerDeregisterResponse = PlatformControllerDeregisterResponses[keyof PlatformControllerDeregisterResponses];

export type PlatformControllerExistsData = {
    body: ApiControllerApiExistsRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/exists';
};

export type PlatformControllerExistsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerExistsError = PlatformControllerExistsErrors[keyof PlatformControllerExistsErrors];

export type PlatformControllerExistsResponses = {
    /**
     * A successful response.
     */
    200: ApiControllerApiExistsResponse;
};

export type PlatformControllerExistsResponse = PlatformControllerExistsResponses[keyof PlatformControllerExistsResponses];

export type PlatformControllerClearFeaturesData = {
    body: ControllerApiClearFeaturesRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/features';
};

export type PlatformControllerClearFeaturesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerClearFeaturesError = PlatformControllerClearFeaturesErrors[keyof PlatformControllerClearFeaturesErrors];

export type PlatformControllerClearFeaturesResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiClearFeaturesResponse;
};

export type PlatformControllerClearFeaturesResponse = PlatformControllerClearFeaturesResponses[keyof PlatformControllerClearFeaturesResponses];

export type PlatformControllerSetFeaturesData = {
    body: ControllerApiSetFeaturesRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/features';
};

export type PlatformControllerSetFeaturesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerSetFeaturesError = PlatformControllerSetFeaturesErrors[keyof PlatformControllerSetFeaturesErrors];

export type PlatformControllerSetFeaturesResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiSetFeaturesResponse;
};

export type PlatformControllerSetFeaturesResponse = PlatformControllerSetFeaturesResponses[keyof PlatformControllerSetFeaturesResponses];

export type PlatformControllerGetData = {
    body: ApiControllerApiGetRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/get';
};

export type PlatformControllerGetErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerGetError = PlatformControllerGetErrors[keyof PlatformControllerGetErrors];

export type PlatformControllerGetResponses = {
    /**
     * A successful response.
     */
    200: ApiControllerApiGetResponse;
};

export type PlatformControllerGetResponse = PlatformControllerGetResponses[keyof PlatformControllerGetResponses];

export type PlatformGetControllerNotificationsData = {
    body: ControllerApiGetNotificationsRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/notifications';
};

export type PlatformGetControllerNotificationsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformGetControllerNotificationsError = PlatformGetControllerNotificationsErrors[keyof PlatformGetControllerNotificationsErrors];

export type PlatformGetControllerNotificationsResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiGetNotificationsResponse;
};

export type PlatformGetControllerNotificationsResponse = PlatformGetControllerNotificationsResponses[keyof PlatformGetControllerNotificationsResponses];

export type PlatformControllerRegisterData = {
    body: ControllerApiRegisterRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/register';
};

export type PlatformControllerRegisterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerRegisterError = PlatformControllerRegisterErrors[keyof PlatformControllerRegisterErrors];

export type PlatformControllerRegisterResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiRegisterResponse;
};

export type PlatformControllerRegisterResponse = PlatformControllerRegisterResponses[keyof PlatformControllerRegisterResponses];

export type PlatformControllerUpdateData = {
    body: ApiControllerApiUpdateRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/update';
};

export type PlatformControllerUpdateErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformControllerUpdateError = PlatformControllerUpdateErrors[keyof PlatformControllerUpdateErrors];

export type PlatformControllerUpdateResponses = {
    /**
     * A successful response.
     */
    200: ApiControllerApiUpdateResponse;
};

export type PlatformControllerUpdateResponse = PlatformControllerUpdateResponses[keyof PlatformControllerUpdateResponses];

export type PlatformGetControllerUrlData = {
    body: ControllerApiGetUrlRequest;
    path?: never;
    query?: never;
    url: '/v1/controller/url';
};

export type PlatformGetControllerUrlErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformGetControllerUrlError = PlatformGetControllerUrlErrors[keyof PlatformGetControllerUrlErrors];

export type PlatformGetControllerUrlResponses = {
    /**
     * A successful response.
     */
    200: ControllerApiGetUrlResponse;
};

export type PlatformGetControllerUrlResponse = PlatformGetControllerUrlResponses[keyof PlatformGetControllerUrlResponses];

export type PlatformLicenseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/license';
};

export type PlatformLicenseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformLicenseError = PlatformLicenseErrors[keyof PlatformLicenseErrors];

export type PlatformLicenseResponses = {
    /**
     * A successful response.
     */
    200: MaintenanceApiLicenseResponse;
};

export type PlatformLicenseResponse = PlatformLicenseResponses[keyof PlatformLicenseResponses];

export type PlatformReleaseLeaseData = {
    body: LeaseReleaseRequest;
    path?: never;
    query?: never;
    url: '/v1/locks/lease';
};

export type PlatformReleaseLeaseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformReleaseLeaseError = PlatformReleaseLeaseErrors[keyof PlatformReleaseLeaseErrors];

export type PlatformReleaseLeaseResponses = {
    /**
     * A successful response.
     */
    200: LeaseReleaseResponse;
};

export type PlatformReleaseLeaseResponse = PlatformReleaseLeaseResponses[keyof PlatformReleaseLeaseResponses];

export type PlatformLeaseResourceData = {
    body: LocksApiLeaseCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/locks/lease';
};

export type PlatformLeaseResourceErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformLeaseResourceError = PlatformLeaseResourceErrors[keyof PlatformLeaseResourceErrors];

export type PlatformLeaseResourceResponses = {
    /**
     * A successful response.
     */
    200: LocksApiLeaseCreateResponse;
};

export type PlatformLeaseResourceResponse = PlatformLeaseResourceResponses[keyof PlatformLeaseResourceResponses];

export type PlatformUpdateLeaseData = {
    body: LocksApiLeaseUpdateRequest;
    path?: never;
    query?: never;
    url: '/v1/locks/lease';
};

export type PlatformUpdateLeaseErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformUpdateLeaseError = PlatformUpdateLeaseErrors[keyof PlatformUpdateLeaseErrors];

export type PlatformUpdateLeaseResponses = {
    /**
     * A successful response.
     */
    200: LocksApiLeaseUpdateResponse;
};

export type PlatformUpdateLeaseResponse = PlatformUpdateLeaseResponses[keyof PlatformUpdateLeaseResponses];

export type PlatformNotificationsGetData = {
    body: ApiNotificationApiGetRequest;
    path?: never;
    query?: never;
    url: '/v1/notifications/get';
};

export type PlatformNotificationsGetErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformNotificationsGetError = PlatformNotificationsGetErrors[keyof PlatformNotificationsGetErrors];

export type PlatformNotificationsGetResponses = {
    /**
     * A successful response.
     */
    200: ApiNotificationApiGetResponse;
};

export type PlatformNotificationsGetResponse = PlatformNotificationsGetResponses[keyof PlatformNotificationsGetResponses];

export type PlatformPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/ping';
};

export type PlatformPingErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformPingError = PlatformPingErrors[keyof PlatformPingErrors];

export type PlatformPingResponses = {
    /**
     * A successful response.
     */
    200: MaintenanceApiPingResponse;
};

export type PlatformPingResponse = PlatformPingResponses[keyof PlatformPingResponses];

export type PlatformListResourceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/resource-types';
};

export type PlatformListResourceTypesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformListResourceTypesError = PlatformListResourceTypesErrors[keyof PlatformListResourceTypesErrors];

export type PlatformListResourceTypesResponses = {
    /**
     * A successful response.
     */
    200: MiscApiListResourceTypesResponse;
};

export type PlatformListResourceTypesResponse = PlatformListResourceTypesResponses[keyof PlatformListResourceTypesResponses];

export type PlatformSubscriptionAttachFilterData = {
    body: SubscriptionApiAttachFilterRequest;
    path?: never;
    query?: never;
    url: '/v1/subscription/attach-filter';
};

export type PlatformSubscriptionAttachFilterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformSubscriptionAttachFilterError = PlatformSubscriptionAttachFilterErrors[keyof PlatformSubscriptionAttachFilterErrors];

export type PlatformSubscriptionAttachFilterResponses = {
    /**
     * A successful response.
     */
    200: SubscriptionApiAttachFilterResponse;
};

export type PlatformSubscriptionAttachFilterResponse = PlatformSubscriptionAttachFilterResponses[keyof PlatformSubscriptionAttachFilterResponses];

export type PlatformSubscriptionDetachFilterData = {
    body: SubscriptionApiDetachFilterRequest;
    path?: never;
    query?: never;
    url: '/v1/subscription/detach-filter';
};

export type PlatformSubscriptionDetachFilterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PlatformSubscriptionDetachFilterError = PlatformSubscriptionDetachFilterErrors[keyof PlatformSubscriptionDetachFilterErrors];

export type PlatformSubscriptionDetachFilterResponses = {
    /**
     * A successful response.
     */
    200: SubscriptionApiDetachFilterResponse;
};

export type PlatformSubscriptionDetachFilterResponse = PlatformSubscriptionDetachFilterResponses[keyof PlatformSubscriptionDetachFilterResponses];
