// Regression tests for the "released software with no docker image" guard (MILAB-6872).
//
// The trap: an image is autogenerated only for python and conda artifacts, so a
// java / R / binary entrypoint without an explicit `docker:` block publishes a
// descriptor the k8s runner cannot use, and the command fails at runtime with
// "docker image is not specified". Every installation is k8s-based.

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import type winston from "winston";
import { PackageInfo } from "../package-info";
import { Core } from "../core";
import {
  assertDockerCoverage,
  descriptorHasNoDockerVariant,
  softwareEntrypointsWithoutDocker,
  type DockerCoverage,
} from "../docker-coverage";
import { NO_SOFTWARE_PLACEHOLDER } from "../../defaults";

const mockLogger = {
  info: vi.fn(),
  warn: vi.fn(),
  debug: vi.fn(),
  error: vi.fn(),
} as unknown as winston.Logger;

// The autogenerated python image resolves its run environment through
// node_modules, which a /tmp fixture does not have. The coverage check only asks
// whether the docker companion exists, so the options it would carry are stubbed.
vi.mock("../docker-python", () => ({
  prepareDockerOptions: vi.fn().mockReturnValue({
    context: "/tmp/test-context",
    dockerfile: "/tmp/test-dockerfile",
    entrypoint: [],
  }),
}));

const JAVA_ARTIFACT = {
  type: "java",
  registry: "test-registry",
  environment: "@platforma-open/milaboratories.runenv-java-corretto:21.0.2.13.1",
  root: "./dld",
};

const javaEntrypoint = (withDocker: boolean) => ({
  binary: { artifact: JAVA_ARTIFACT, cmd: ["java", "-jar", "{pkg}/tool.jar"] },
  ...(withDocker
    ? { docker: { artifact: { context: "dld" }, cmd: ["java", "-jar", "/app/tool.jar"] } }
    : {}),
});

const pythonEntrypoint = {
  binary: {
    artifact: {
      type: "python",
      registry: "test-registry",
      environment: "@platforma-open/milaboratories.runenv-python-3:3.12.10",
      root: "./src",
      dependencies: { toolset: "pip", requirements: "requirements.txt" },
    },
    cmd: ["python", "{pkg}/main.py"],
  },
};

describe("softwareEntrypointsWithoutDocker", () => {
  let tempDir: string;
  let packageRoot: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join("/tmp", "docker-coverage-test-"));
    packageRoot = path.join(tempDir, "package");
    fs.mkdirSync(packageRoot, { recursive: true });
    vi.clearAllMocks();
  });

  afterEach(() => {
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  });

  const uncovered = (blockSoftware: Record<string, unknown>): string[] => {
    fs.writeFileSync(
      path.join(packageRoot, "package.json"),
      JSON.stringify(
        { name: "test-package", version: "1.0.0", "block-software": blockSoftware },
        null,
        2,
      ),
    );
    return softwareEntrypointsWithoutDocker(
      new PackageInfo(mockLogger, { packageRoot }).entrypoints,
    );
  };

  it("flags a java entrypoint with no docker block", () => {
    expect(uncovered({ entrypoints: { main: javaEntrypoint(false) } })).toEqual(["main"]);
  });

  it("passes a java entrypoint that declares docker explicitly", () => {
    expect(uncovered({ entrypoints: { main: javaEntrypoint(true) } })).toEqual([]);
  });

  it("passes python, whose image is autogenerated", () => {
    expect(uncovered({ entrypoints: { main: pythonEntrypoint } })).toEqual([]);
  });

  it("passes a docker-only entrypoint", () => {
    expect(
      uncovered({
        entrypoints: { main: { docker: { artifact: { context: "dld" }, cmd: ["tool"] } } },
      }),
    ).toEqual([]);
  });

  // The ':docker' suffix marks the companion PackageInfo generates, but entrypoint
  // names are barely constrained, so a package may declare one called 'main:docker'.
  // Reading the suffix as "generated, already covered" would let it hide there.
  it("flags a binary-only entrypoint that is itself named with the companion suffix", () => {
    expect(uncovered({ entrypoints: { "main:docker": javaEntrypoint(false) } })).toEqual([
      "main:docker",
    ]);
  });

  it("passes an entrypoint named with the suffix once it declares an image", () => {
    expect(uncovered({ entrypoints: { "main:docker": javaEntrypoint(true) } })).toEqual([]);
  });

  it("skips run environments, whose image is baked into the software that uses them", () => {
    expect(
      uncovered({
        entrypoints: {
          jre: {
            environment: {
              artifact: {
                registry: "test-registry",
                runtime: "java",
                "java-version": "21",
                roots: { "linux-x64": "./env" },
                binDir: ".",
              },
            },
          },
        },
      }),
    ).toEqual([]);
  });

  it("skips assets, which are data and not runnable", () => {
    expect(
      uncovered({
        entrypoints: { data: { asset: { registry: "test-registry", root: "./data" } } },
      }),
    ).toEqual([]);
  });

  it("names only the uncovered entrypoints of a mixed package", () => {
    expect(
      uncovered({
        entrypoints: {
          "java-tool": javaEntrypoint(false),
          "java-tool-dockerized": javaEntrypoint(true),
          "python-tool": pythonEntrypoint,
        },
      }),
    ).toEqual(["java-tool"]);
  });

  it("defaults requireDocker to true and honours an explicit opt-out", () => {
    const write = (blockSoftware: Record<string, unknown>) => {
      fs.writeFileSync(
        path.join(packageRoot, "package.json"),
        JSON.stringify({ name: "p", version: "1.0.0", "block-software": blockSoftware }, null, 2),
      );
      return new PackageInfo(mockLogger, { packageRoot }).requireDocker;
    };

    expect(write({ entrypoints: { main: javaEntrypoint(false) } })).toBe(true);
    expect(write({ requireDocker: false, entrypoints: { main: javaEntrypoint(false) } })).toBe(
      false,
    );
  });

  it("stops a CI build before it writes the descriptor", () => {
    const ci = process.env.CI;
    process.env.CI = "true";

    fs.writeFileSync(
      path.join(packageRoot, "package.json"),
      JSON.stringify({
        name: "test-package",
        version: "1.0.0",
        "block-software": { entrypoints: { main: javaEntrypoint(false) } },
      }),
    );

    const core = new Core(mockLogger, { packageRoot });
    try {
      expect(() => core.buildSwJsonFiles()).toThrow(/produce no docker image/);
    } finally {
      if (ci === undefined) delete process.env.CI;
      else process.env.CI = ci;
    }
  });
});

describe("descriptorHasNoDockerVariant", () => {
  const binary = { type: "java", registry: "milaboratories", package: "sw/1.0.0.tgz", cmd: ["x"] };

  it("flags a rendered descriptor with only a binary variant", () => {
    expect(descriptorHasNoDockerVariant({ binary })).toBe(true);
  });

  it("passes a descriptor that carries an image", () => {
    expect(descriptorHasNoDockerVariant({ binary, docker: { tag: "reg/img:tag" } })).toBe(false);
  });

  it("passes a run environment, which is not runnable software", () => {
    expect(descriptorHasNoDockerVariant({ runEnv: { type: "java" } })).toBe(false);
  });

  it("passes a dev-mode descriptor, which points at a directory and never runs on a cluster", () => {
    expect(descriptorHasNoDockerVariant({ local: { path: "/src" }, isDev: true })).toBe(false);
  });

  it("passes the no-software placeholder", () => {
    expect(
      descriptorHasNoDockerVariant({
        isDev: true,
        binary: { type: "binary", registry: NO_SOFTWARE_PLACEHOLDER, cmd: ["true"] },
      }),
    ).toBe(false);
  });

  it("ignores anything that is not a descriptor object", () => {
    expect(descriptorHasNoDockerVariant(null)).toBe(false);
    expect(descriptorHasNoDockerVariant("{}")).toBe(false);
  });
});

const UNCOVERED: DockerCoverage = {
  softwareWithoutDocker: ["main"],
  requirementWaived: false,
};

describe("assertDockerCoverage", () => {
  let ci: string | undefined;

  beforeEach(() => {
    ci = process.env.CI;
    process.env.CI = "true";
  });

  afterEach(() => {
    if (ci === undefined) delete process.env.CI;
    else process.env.CI = ci;
  });

  it("throws when CI describes software no k8s install can run", () => {
    expect(() => assertDockerCoverage(UNCOVERED)).toThrow(/produce no docker image/);
  });

  it("names the uncovered entrypoints", () => {
    expect(() =>
      assertDockerCoverage({ ...UNCOVERED, softwareWithoutDocker: ["main", "low-memory"] }),
    ).toThrow(/low-memory/);
  });

  it("points at the requireDocker opt-out", () => {
    expect(() => assertDockerCoverage(UNCOVERED)).toThrow(/"requireDocker": false/);
  });

  it("accepts a package that declared itself binary-only", () => {
    expect(() => assertDockerCoverage({ ...UNCOVERED, requirementWaived: true })).not.toThrow();
  });

  it("accepts a package whose software is fully covered", () => {
    expect(() => assertDockerCoverage({ ...UNCOVERED, softwareWithoutDocker: [] })).not.toThrow();
  });

  it("stays out of the way outside CI, where a partial package is normal mid-edit", () => {
    delete process.env.CI;
    expect(() => assertDockerCoverage(UNCOVERED)).not.toThrow();
  });
});
