// @generated by protobuf-ts 2.11.1 with parameter client_generic,optimize_speed,generate_dependencies,force_server_none
// @generated from protobuf file "github.com/milaboratory/pl/plapi/plapiproto/ws-test.proto" (package "MiLaboratories.PL.WSTest", syntax proto3)
// tslint:disable
//
//
// This is dirty implementation of custom protocol for fast WebSocket support testing in
// environments with ZScaler or other similar MITM corporate proxies.
//
//
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message MiLaboratories.PL.WSTest.PingWS
 */
export interface PingWS {
}
/**
 * @generated from protobuf message MiLaboratories.PL.WSTest.PingWS.Request
 */
export interface PingWS_Request {
    /**
     * @generated from protobuf field: int32 request_id = 1
     */
    requestId: number;
    /**
     * @generated from protobuf field: int32 replies_count = 2
     */
    repliesCount: number; // amount of Response messages to send (0 - send nothing)
    /**
     * @generated from protobuf field: bool close = 3
     */
    close: boolean; // make server to close connection after sending responses
}
/**
 * @generated from protobuf message MiLaboratories.PL.WSTest.PingWS.Response
 */
export interface PingWS_Response {
    /**
     * @generated from protobuf field: int32 request_id = 1
     */
    requestId: number;
    /**
     * @generated from protobuf field: int32 reply_id = 2
     */
    replyId: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class PingWS$Type extends MessageType<PingWS> {
    constructor() {
        super("MiLaboratories.PL.WSTest.PingWS", []);
    }
    create(value?: PartialMessage<PingWS>): PingWS {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PingWS>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PingWS): PingWS {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PingWS, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MiLaboratories.PL.WSTest.PingWS
 */
export const PingWS = new PingWS$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PingWS_Request$Type extends MessageType<PingWS_Request> {
    constructor() {
        super("MiLaboratories.PL.WSTest.PingWS.Request", [
            { no: 1, name: "request_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "replies_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "close", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PingWS_Request>): PingWS_Request {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = 0;
        message.repliesCount = 0;
        message.close = false;
        if (value !== undefined)
            reflectionMergePartial<PingWS_Request>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PingWS_Request): PingWS_Request {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 request_id */ 1:
                    message.requestId = reader.int32();
                    break;
                case /* int32 replies_count */ 2:
                    message.repliesCount = reader.int32();
                    break;
                case /* bool close */ 3:
                    message.close = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PingWS_Request, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 request_id = 1; */
        if (message.requestId !== 0)
            writer.tag(1, WireType.Varint).int32(message.requestId);
        /* int32 replies_count = 2; */
        if (message.repliesCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.repliesCount);
        /* bool close = 3; */
        if (message.close !== false)
            writer.tag(3, WireType.Varint).bool(message.close);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MiLaboratories.PL.WSTest.PingWS.Request
 */
export const PingWS_Request = new PingWS_Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PingWS_Response$Type extends MessageType<PingWS_Response> {
    constructor() {
        super("MiLaboratories.PL.WSTest.PingWS.Response", [
            { no: 1, name: "request_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "reply_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<PingWS_Response>): PingWS_Response {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = 0;
        message.replyId = 0;
        if (value !== undefined)
            reflectionMergePartial<PingWS_Response>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PingWS_Response): PingWS_Response {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 request_id */ 1:
                    message.requestId = reader.int32();
                    break;
                case /* int32 reply_id */ 2:
                    message.replyId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PingWS_Response, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 request_id = 1; */
        if (message.requestId !== 0)
            writer.tag(1, WireType.Varint).int32(message.requestId);
        /* int32 reply_id = 2; */
        if (message.replyId !== 0)
            writer.tag(2, WireType.Varint).int32(message.replyId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MiLaboratories.PL.WSTest.PingWS.Response
 */
export const PingWS_Response = new PingWS_Response$Type();
