name: _build

on:
  workflow_call: {}

env:
  BODY_LIMIT: "1048576000"

jobs:
  build:
    runs-on: dev-pl-sdk
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_ZEN_APP_ID }}
          private-key: ${{ secrets.GH_ZEN_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          npmjs-token: ${{ secrets.NPMJS_TOKEN }}
          github-token: ${{ steps.app-token.outputs.token }}
          aws-iam-role: ${{ secrets.AWS_CI_IAM_MONOREPO_SIMPLE_ROLE }}
          turbo-s3-bucket: ${{ secrets.AWS_CI_TURBOREPO_S3_BUCKET }}
          quay-username: ${{ secrets.QUAY_USERNAME }}
          quay-robot-token: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Check pnpm-workspace.yaml consistency
        run: |
          if git diff --name-only origin/main..HEAD | grep -q -E '^pnpm-workspace.yaml$'; then
            if ! git diff --name-only origin/main..HEAD | grep -q -E '^pnpm-lock.yaml$'; then
              echo "::error::Changes in pnpm-workspace.yaml detected, but no updates in pnpm-lock.yaml"
              exit 1
            fi
          fi

      - name: Build
        env:
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PL_DOCKER_REGISTRY_PUSH_TO: "quay.io/milaboratories/pl-containers"
        run: pnpm run ci:build:local-rel
