name: Check review
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'

  pull_request_review:
    types: [submitted]

jobs:
  run:
    uses: milaboratory/github-ci/.github/workflows/require-review.yaml@monorepo-js
