name: Test K8S
on:
  merge_group:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4-beta
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init
    uses: milaboratory/github-ci/.github/workflows/node-simple-pnpm-k8s.yaml@v4-beta
    with:
      app-name: Platforma SDK Ggoogle Batch Int Tests
      app-name-slug: 'platforma-sdk-gcp'
      gha-runner-label: 'dev-gke'
      node-version: '20.x'
      pl-version: 'main'
      pnpm-build-command: '--filter "*/workflow-tengo*"'
      pnpm-test-command: '--filter="@platforma-sdk/workflow-tengo-tests" -- --maxConcurrency=5 --minWorkers=50 --maxWorkers=50 --testTimeout=300000'
      helm-release-name: 'pl-dev-gcp'
      helm-chart-values-file: 'helm/gcp/values.yaml'
      namespace: 'dev-gke'
      npmrc-config: |
        {
          "registries": {
            "https://registry.npmjs.org/": {
              "scopes": ["milaboratories", "platforma-sdk"],
              "tokenVar": "NPMJS_TOKEN"
            },
            "https://npm.pkg.github.com/": {
              "scopes": ["milaboratory"],
              "tokenVar": "NODE_AUTH_TOKEN"
            }
          }
        }
      env: |
        { "BODY_LIMIT": "1048576000", 
          "TEST_TIMEOUT": "5m" }
    secrets:
      env: |
        { "PL_CI_TEST_USER": ${{ toJSON(secrets.PL_CI_TEST_USER) }},
          "PL_CI_TEST_PASSWORD": ${{ toJSON(secrets.PL_CI_TEST_PASSWORD) }},
          "NPMJS_TOKEN": ${{ toJSON(secrets.NPMJS_TOKEN) }},
          "GCLOUD_CI_GKE_BUCKET_NAME": ${{ toJSON(secrets.GCLOUD_CI_GKE_BUCKET_NAME) }} }

      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_PL_SDK_CHANNEL }}
